<?php

/**
 * BaseagClientMedicalStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_id
 * @property timestamp $time_stamp
 * @property integer $client_medical_status_type_id
 * @property agClient $agClient
 * @property agClientMedicalStatusType $agClientMedicalStatusType
 * 
 * @method integer                   getId()                            Returns the current record's "id" value
 * @method integer                   getClientId()                      Returns the current record's "client_id" value
 * @method timestamp                 getTimeStamp()                     Returns the current record's "time_stamp" value
 * @method integer                   getClientMedicalStatusTypeId()     Returns the current record's "client_medical_status_type_id" value
 * @method agClient                  getAgClient()                      Returns the current record's "agClient" value
 * @method agClientMedicalStatusType getAgClientMedicalStatusType()     Returns the current record's "agClientMedicalStatusType" value
 * @method agClientMedicalStatus     setId()                            Sets the current record's "id" value
 * @method agClientMedicalStatus     setClientId()                      Sets the current record's "client_id" value
 * @method agClientMedicalStatus     setTimeStamp()                     Sets the current record's "time_stamp" value
 * @method agClientMedicalStatus     setClientMedicalStatusTypeId()     Sets the current record's "client_medical_status_type_id" value
 * @method agClientMedicalStatus     setAgClient()                      Sets the current record's "agClient" value
 * @method agClientMedicalStatus     setAgClientMedicalStatusType()     Sets the current record's "agClientMedicalStatusType" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagClientMedicalStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_client_medical_status');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('client_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('time_stamp', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('client_medical_status_type_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('UX_agClientMedicalStatus', array(
             'fields' => 
             array(
              0 => 'client_id',
              1 => 'time_stamp',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agClient', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('agClientMedicalStatusType', array(
             'local' => 'client_medical_status_type_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}