<?php

/**
 * BaseagPersonMjAgReligion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $person_id
 * @property integer $religion_id
 * @property agPerson $agPerson
 * @property agReligion $agReligion
 * 
 * @method integer              getId()          Returns the current record's "id" value
 * @method integer              getPersonId()    Returns the current record's "person_id" value
 * @method integer              getReligionId()  Returns the current record's "religion_id" value
 * @method agPerson             getAgPerson()    Returns the current record's "agPerson" value
 * @method agReligion           getAgReligion()  Returns the current record's "agReligion" value
 * @method agPersonMjAgReligion setId()          Sets the current record's "id" value
 * @method agPersonMjAgReligion setPersonId()    Sets the current record's "person_id" value
 * @method agPersonMjAgReligion setReligionId()  Sets the current record's "religion_id" value
 * @method agPersonMjAgReligion setAgPerson()    Sets the current record's "agPerson" value
 * @method agPersonMjAgReligion setAgReligion()  Sets the current record's "agReligion" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagPersonMjAgReligion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_person_mj_ag_religion');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('person_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('religion_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('UX_ag_person_mj_ag_religion', array(
             'fields' => 
             array(
              0 => 'person_id',
              1 => 'religion_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agPerson', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('agReligion', array(
             'local' => 'religion_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}