<?php

/**
 * BaseagClientGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property integer $client_group_type_id
 * @property integer $client_group_leader_id
 * @property agClientGroupType $agClientGroupType
 * @property agClient $agClient
 * @property agEntity $agEntity
 * @property Doctrine_Collection $agClientGroupComposition
 * @property Doctrine_Collection $agClientGroupMembership
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method integer             getEntityId()                 Returns the current record's "entity_id" value
 * @method integer             getClientGroupTypeId()        Returns the current record's "client_group_type_id" value
 * @method integer             getClientGroupLeaderId()      Returns the current record's "client_group_leader_id" value
 * @method agClientGroupType   getAgClientGroupType()        Returns the current record's "agClientGroupType" value
 * @method agClient            getAgClient()                 Returns the current record's "agClient" value
 * @method agEntity            getAgEntity()                 Returns the current record's "agEntity" value
 * @method Doctrine_Collection getAgClientGroupComposition() Returns the current record's "agClientGroupComposition" collection
 * @method Doctrine_Collection getAgClientGroupMembership()  Returns the current record's "agClientGroupMembership" collection
 * @method agClientGroup       setId()                       Sets the current record's "id" value
 * @method agClientGroup       setEntityId()                 Sets the current record's "entity_id" value
 * @method agClientGroup       setClientGroupTypeId()        Sets the current record's "client_group_type_id" value
 * @method agClientGroup       setClientGroupLeaderId()      Sets the current record's "client_group_leader_id" value
 * @method agClientGroup       setAgClientGroupType()        Sets the current record's "agClientGroupType" value
 * @method agClientGroup       setAgClient()                 Sets the current record's "agClient" value
 * @method agClientGroup       setAgEntity()                 Sets the current record's "agEntity" value
 * @method agClientGroup       setAgClientGroupComposition() Sets the current record's "agClientGroupComposition" collection
 * @method agClientGroup       setAgClientGroupMembership()  Sets the current record's "agClientGroupMembership" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagClientGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_client_group');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('entity_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('client_group_type_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('client_group_leader_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));


        $this->index('UX_agClientGroup', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agClientGroupType', array(
             'local' => 'client_group_type_id',
             'foreign' => 'id'));

        $this->hasOne('agClient', array(
             'local' => 'client_group_leader_id',
             'foreign' => 'id'));

        $this->hasOne('agEntity', array(
             'local' => 'entity_id',
             'foreign' => 'id'));

        $this->hasMany('agClientGroupComposition', array(
             'local' => 'id',
             'foreign' => 'client_group_id'));

        $this->hasMany('agClientGroupMembership', array(
             'local' => 'id',
             'foreign' => 'client_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}