<?php

/**
 * BaseagMessageElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $message_id
 * @property integer $message_element_type_id
 * @property blob $value
 * @property agMessage $agMessage
 * @property agMessageElementType $agMessageElementType
 * 
 * @method integer              getId()                      Returns the current record's "id" value
 * @method integer              getMessageId()               Returns the current record's "message_id" value
 * @method integer              getMessageElementTypeId()    Returns the current record's "message_element_type_id" value
 * @method blob                 getValue()                   Returns the current record's "value" value
 * @method agMessage            getAgMessage()               Returns the current record's "agMessage" value
 * @method agMessageElementType getAgMessageElementType()    Returns the current record's "agMessageElementType" value
 * @method agMessageElement     setId()                      Sets the current record's "id" value
 * @method agMessageElement     setMessageId()               Sets the current record's "message_id" value
 * @method agMessageElement     setMessageElementTypeId()    Sets the current record's "message_element_type_id" value
 * @method agMessageElement     setValue()                   Sets the current record's "value" value
 * @method agMessageElement     setAgMessage()               Sets the current record's "agMessage" value
 * @method agMessageElement     setAgMessageElementType()    Sets the current record's "agMessageElementType" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagMessageElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_message_element');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('message_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('message_element_type_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('value', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));


        $this->index('agMessageElement_unq', array(
             'fields' => 
             array(
              0 => 'message_id',
              1 => 'message_element_type_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agMessage', array(
             'local' => 'message_id',
             'foreign' => 'id'));

        $this->hasOne('agMessageElementType', array(
             'local' => 'message_element_type_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}