<?php

/**
 * BaseagRawSkillMap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $raw_skill_id
 * @property integer $skill_id
 * @property agSkill $agSkill
 * @property agRawSkill $agRawSkill
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getRawSkillId()   Returns the current record's "raw_skill_id" value
 * @method integer       getSkillId()      Returns the current record's "skill_id" value
 * @method agSkill       getAgSkill()      Returns the current record's "agSkill" value
 * @method agRawSkill    getAgRawSkill()   Returns the current record's "agRawSkill" value
 * @method agRawSkillMap setId()           Sets the current record's "id" value
 * @method agRawSkillMap setRawSkillId()   Sets the current record's "raw_skill_id" value
 * @method agRawSkillMap setSkillId()      Sets the current record's "skill_id" value
 * @method agRawSkillMap setAgSkill()      Sets the current record's "agSkill" value
 * @method agRawSkillMap setAgRawSkill()   Sets the current record's "agRawSkill" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagRawSkillMap extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_raw_skill_map');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('raw_skill_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('skill_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('UX_agRawSkillMap', array(
             'fields' => 
             array(
              0 => 'raw_skill_id',
              1 => 'skill_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agSkill', array(
             'local' => 'skill_id',
             'foreign' => 'id'));

        $this->hasOne('agRawSkill', array(
             'local' => 'raw_skill_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}