<?php

/**
 * BaseagClientGroupMembership
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_group_id
 * @property integer $client_id
 * @property agClient $agClient
 * @property agClientGroup $agClientGroup
 * 
 * @method integer                 getId()              Returns the current record's "id" value
 * @method integer                 getClientGroupId()   Returns the current record's "client_group_id" value
 * @method integer                 getClientId()        Returns the current record's "client_id" value
 * @method agClient                getAgClient()        Returns the current record's "agClient" value
 * @method agClientGroup           getAgClientGroup()   Returns the current record's "agClientGroup" value
 * @method agClientGroupMembership setId()              Sets the current record's "id" value
 * @method agClientGroupMembership setClientGroupId()   Sets the current record's "client_group_id" value
 * @method agClientGroupMembership setClientId()        Sets the current record's "client_id" value
 * @method agClientGroupMembership setAgClient()        Sets the current record's "agClient" value
 * @method agClientGroupMembership setAgClientGroup()   Sets the current record's "agClientGroup" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagClientGroupMembership extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_client_group_membership');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('client_group_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('client_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));


        $this->index('UX_agClientGroupMembership', array(
             'fields' => 
             array(
              0 => 'client_group_id',
              1 => 'client_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agClient', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('agClientGroup', array(
             'local' => 'client_group_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}