<?php

/**
 * BaseagGlobalParam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $datapoint
 * @property string $value
 * @property agHost $agHost
 * 
 * @method integer       getId()        Returns the current record's "id" value
 * @method string        getDatapoint() Returns the current record's "datapoint" value
 * @method string        getValue()     Returns the current record's "value" value
 * @method agHost        getAgHost()    Returns the current record's "agHost" value
 * @method agGlobalParam setId()        Sets the current record's "id" value
 * @method agGlobalParam setDatapoint() Sets the current record's "datapoint" value
 * @method agGlobalParam setValue()     Sets the current record's "value" value
 * @method agGlobalParam setAgHost()    Sets the current record's "agHost" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagGlobalParam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_global_param');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('datapoint', 'string', 128, array(
             'primary' => true,
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('value', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agHost', array(
             'local' => 'id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}