<?php

/**
 * BaseagMessageDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $message_id
 * @property timestamp $time_stamp
 * @property integer $message_status_id
 * @property agMessage $agMessage
 * @property agMessageStatus $agMessageStatus
 * 
 * @method integer         getId()                Returns the current record's "id" value
 * @method integer         getMessageId()         Returns the current record's "message_id" value
 * @method timestamp       getTimeStamp()         Returns the current record's "time_stamp" value
 * @method integer         getMessageStatusId()   Returns the current record's "message_status_id" value
 * @method agMessage       getAgMessage()         Returns the current record's "agMessage" value
 * @method agMessageStatus getAgMessageStatus()   Returns the current record's "agMessageStatus" value
 * @method agMessageDetail setId()                Sets the current record's "id" value
 * @method agMessageDetail setMessageId()         Sets the current record's "message_id" value
 * @method agMessageDetail setTimeStamp()         Sets the current record's "time_stamp" value
 * @method agMessageDetail setMessageStatusId()   Sets the current record's "message_status_id" value
 * @method agMessageDetail setAgMessage()         Sets the current record's "agMessage" value
 * @method agMessageDetail setAgMessageStatus()   Sets the current record's "agMessageStatus" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagMessageDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_message_detail');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('message_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('time_stamp', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('message_status_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('agMessageDetail_unq', array(
             'fields' => 
             array(
              0 => 'message_id',
              1 => 'time_stamp',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agMessage', array(
             'local' => 'message_id',
             'foreign' => 'id'));

        $this->hasOne('agMessageStatus', array(
             'local' => 'message_status_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}