<?php

/**
 * BaseagImport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $person_id
 * @property integer $import_type_id
 * @property gzip $filename
 * @property agImportType $agImportType
 * @property agPerson $agPerson
 * @property Doctrine_Collection $agPersonLastImport
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getPersonId()           Returns the current record's "person_id" value
 * @method integer             getImportTypeId()       Returns the current record's "import_type_id" value
 * @method gzip                getFilename()           Returns the current record's "filename" value
 * @method agImportType        getAgImportType()       Returns the current record's "agImportType" value
 * @method agPerson            getAgPerson()           Returns the current record's "agPerson" value
 * @method Doctrine_Collection getAgPersonLastImport() Returns the current record's "agPersonLastImport" collection
 * @method agImport            setId()                 Sets the current record's "id" value
 * @method agImport            setPersonId()           Sets the current record's "person_id" value
 * @method agImport            setImportTypeId()       Sets the current record's "import_type_id" value
 * @method agImport            setFilename()           Sets the current record's "filename" value
 * @method agImport            setAgImportType()       Sets the current record's "agImportType" value
 * @method agImport            setAgPerson()           Sets the current record's "agPerson" value
 * @method agImport            setAgPersonLastImport() Sets the current record's "agPersonLastImport" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagImport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_import');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('person_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('import_type_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('filename', 'gzip', null, array(
             'type' => 'gzip',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agImportType', array(
             'local' => 'import_type_id',
             'foreign' => 'id'));

        $this->hasOne('agPerson', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasMany('agPersonLastImport', array(
             'local' => 'id',
             'foreign' => 'last_import_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}