<?php

/**
 * BaseagOrganizationBranch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $organization_id
 * @property integer $branch_id
 * @property agOrganization $agOrganization
 * @property agBranch $agBranch
 * 
 * @method integer              getId()              Returns the current record's "id" value
 * @method integer              getOrganizationId()  Returns the current record's "organization_id" value
 * @method integer              getBranchId()        Returns the current record's "branch_id" value
 * @method agOrganization       getAgOrganization()  Returns the current record's "agOrganization" value
 * @method agBranch             getAgBranch()        Returns the current record's "agBranch" value
 * @method agOrganizationBranch setId()              Sets the current record's "id" value
 * @method agOrganizationBranch setOrganizationId()  Sets the current record's "organization_id" value
 * @method agOrganizationBranch setBranchId()        Sets the current record's "branch_id" value
 * @method agOrganizationBranch setAgOrganization()  Sets the current record's "agOrganization" value
 * @method agOrganizationBranch setAgBranch()        Sets the current record's "agBranch" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagOrganizationBranch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_organization_branch');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('organization_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('branch_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('agOrganizationBranch_unq', array(
             'fields' => 
             array(
              0 => 'organization_id',
              1 => 'branch_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agOrganization', array(
             'local' => 'organization_id',
             'foreign' => 'id'));

        $this->hasOne('agBranch', array(
             'local' => 'branch_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}