<?php

/**
 * BaseagMessageReply
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $message_id
 * @property integer $message_reply_argument_id
 * @property blob $value
 * @property agMessage $agMessage
 * @property agMessageReplyArgument $agMessageReplyArgument
 * 
 * @method integer                getId()                        Returns the current record's "id" value
 * @method integer                getMessageId()                 Returns the current record's "message_id" value
 * @method integer                getMessageReplyArgumentId()    Returns the current record's "message_reply_argument_id" value
 * @method blob                   getValue()                     Returns the current record's "value" value
 * @method agMessage              getAgMessage()                 Returns the current record's "agMessage" value
 * @method agMessageReplyArgument getAgMessageReplyArgument()    Returns the current record's "agMessageReplyArgument" value
 * @method agMessageReply         setId()                        Sets the current record's "id" value
 * @method agMessageReply         setMessageId()                 Sets the current record's "message_id" value
 * @method agMessageReply         setMessageReplyArgumentId()    Sets the current record's "message_reply_argument_id" value
 * @method agMessageReply         setValue()                     Sets the current record's "value" value
 * @method agMessageReply         setAgMessage()                 Sets the current record's "agMessage" value
 * @method agMessageReply         setAgMessageReplyArgument()    Sets the current record's "agMessageReplyArgument" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagMessageReply extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_message_reply');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('message_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('message_reply_argument_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('value', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));


        $this->index('agMessageReply_unq', array(
             'fields' => 
             array(
              0 => 'message_id',
              1 => 'message_reply_argument_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agMessage', array(
             'local' => 'message_id',
             'foreign' => 'id'));

        $this->hasOne('agMessageReplyArgument', array(
             'local' => 'message_reply_argument_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}