<?php

/**
 * BaseagMessageTrigger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $message_trigger
 * @property string $description
 * @property Doctrine_Collection $agEventMessageTrigger
 * @property Doctrine_Collection $agDefaultMessageBatchTrigger
 * @property Doctrine_Collection $agShiftTemplateMessage
 * 
 * @method integer             getId()                           Returns the current record's "id" value
 * @method string              getMessageTrigger()               Returns the current record's "message_trigger" value
 * @method string              getDescription()                  Returns the current record's "description" value
 * @method Doctrine_Collection getAgEventMessageTrigger()        Returns the current record's "agEventMessageTrigger" collection
 * @method Doctrine_Collection getAgDefaultMessageBatchTrigger() Returns the current record's "agDefaultMessageBatchTrigger" collection
 * @method Doctrine_Collection getAgShiftTemplateMessage()       Returns the current record's "agShiftTemplateMessage" collection
 * @method agMessageTrigger    setId()                           Sets the current record's "id" value
 * @method agMessageTrigger    setMessageTrigger()               Sets the current record's "message_trigger" value
 * @method agMessageTrigger    setDescription()                  Sets the current record's "description" value
 * @method agMessageTrigger    setAgEventMessageTrigger()        Sets the current record's "agEventMessageTrigger" collection
 * @method agMessageTrigger    setAgDefaultMessageBatchTrigger() Sets the current record's "agDefaultMessageBatchTrigger" collection
 * @method agMessageTrigger    setAgShiftTemplateMessage()       Sets the current record's "agShiftTemplateMessage" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagMessageTrigger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_message_trigger');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('message_trigger', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('UX_MessageTrigger', array(
             'fields' => 
             array(
              0 => 'message_trigger',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agEventMessageTrigger', array(
             'local' => 'id',
             'foreign' => 'message_trigger_id'));

        $this->hasMany('agDefaultMessageBatchTrigger', array(
             'local' => 'id',
             'foreign' => 'message_trigger_id'));

        $this->hasMany('agShiftTemplateMessage', array(
             'local' => 'id',
             'foreign' => 'message_trigger_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}