<?php

/**
 * BaseagAccountMjSfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $account_id
 * @property integer $sf_guard_user_id
 * @property sfGuardUser $sfGuardUser
 * @property agAccount $agAccount
 * 
 * @method integer                getId()               Returns the current record's "id" value
 * @method integer                getAccountId()        Returns the current record's "account_id" value
 * @method integer                getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method sfGuardUser            getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method agAccount              getAgAccount()        Returns the current record's "agAccount" value
 * @method agAccountMjSfGuardUser setId()               Sets the current record's "id" value
 * @method agAccountMjSfGuardUser setAccountId()        Sets the current record's "account_id" value
 * @method agAccountMjSfGuardUser setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method agAccountMjSfGuardUser setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method agAccountMjSfGuardUser setAgAccount()        Sets the current record's "agAccount" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagAccountMjSfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_account_mj_sf_guard_user');
        $this->hasColumn('id', 'integer', 5, array(
             'autoincrement' => true,
             'primary' => true,
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('account_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('UX_ag_account_mj_sf_guard_user', array(
             'fields' => 
             array(
              0 => 'account_id',
              1 => 'sf_guard_user_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasOne('agAccount', array(
             'local' => 'account_id',
             'foreign' => 'id'));
    }
}