<?php

/**
 * BaseagCountryMjAgIso31661Alpha3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property integer $iso_31661_alpha3_id
 * @property agCountry $agCountry
 * @property agIso31661Alpha3 $agIso31661Alpha3
 * 
 * @method integer                     getCountryId()           Returns the current record's "country_id" value
 * @method integer                     getIso31661Alpha3Id()    Returns the current record's "iso_31661_alpha3_id" value
 * @method agCountry                   getAgCountry()           Returns the current record's "agCountry" value
 * @method agIso31661Alpha3            getAgIso31661Alpha3()    Returns the current record's "agIso31661Alpha3" value
 * @method agCountryMjAgIso31661Alpha3 setCountryId()           Sets the current record's "country_id" value
 * @method agCountryMjAgIso31661Alpha3 setIso31661Alpha3Id()    Sets the current record's "iso_31661_alpha3_id" value
 * @method agCountryMjAgIso31661Alpha3 setAgCountry()           Sets the current record's "agCountry" value
 * @method agCountryMjAgIso31661Alpha3 setAgIso31661Alpha3()    Sets the current record's "agIso31661Alpha3" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagCountryMjAgIso31661Alpha3 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_country_mj_ag_iso31661_alpha3');
        $this->hasColumn('country_id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('iso_31661_alpha3_id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agCountry', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasOne('agIso31661Alpha3', array(
             'local' => 'iso_31661_alpha3_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}