<?php

/**
 * BaseagPersonLanguageCompetency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $person_language_id
 * @property integer $language_format_id
 * @property integer $language_competency_id
 * @property agLanguageFormat $agLanguageFormat
 * @property agPersonMjAgLanguage $agPersonMjAgLanguage
 * @property agLanguageCompetency $agLanguageCompetency
 * 
 * @method integer                    getId()                     Returns the current record's "id" value
 * @method integer                    getPersonLanguageId()       Returns the current record's "person_language_id" value
 * @method integer                    getLanguageFormatId()       Returns the current record's "language_format_id" value
 * @method integer                    getLanguageCompetencyId()   Returns the current record's "language_competency_id" value
 * @method agLanguageFormat           getAgLanguageFormat()       Returns the current record's "agLanguageFormat" value
 * @method agPersonMjAgLanguage       getAgPersonMjAgLanguage()   Returns the current record's "agPersonMjAgLanguage" value
 * @method agLanguageCompetency       getAgLanguageCompetency()   Returns the current record's "agLanguageCompetency" value
 * @method agPersonLanguageCompetency setId()                     Sets the current record's "id" value
 * @method agPersonLanguageCompetency setPersonLanguageId()       Sets the current record's "person_language_id" value
 * @method agPersonLanguageCompetency setLanguageFormatId()       Sets the current record's "language_format_id" value
 * @method agPersonLanguageCompetency setLanguageCompetencyId()   Sets the current record's "language_competency_id" value
 * @method agPersonLanguageCompetency setAgLanguageFormat()       Sets the current record's "agLanguageFormat" value
 * @method agPersonLanguageCompetency setAgPersonMjAgLanguage()   Sets the current record's "agPersonMjAgLanguage" value
 * @method agPersonLanguageCompetency setAgLanguageCompetency()   Sets the current record's "agLanguageCompetency" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagPersonLanguageCompetency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_person_language_competency');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('person_language_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('language_format_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('language_competency_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agLanguageFormat', array(
             'local' => 'language_format_id',
             'foreign' => 'id'));

        $this->hasOne('agPersonMjAgLanguage', array(
             'local' => 'person_language_id',
             'foreign' => 'id'));

        $this->hasOne('agLanguageCompetency', array(
             'local' => 'language_competency_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}