<?php

/**
 * BaseagEventDescription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property gzip $description
 * @property agEvent $agEvent
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method integer            getEventId()     Returns the current record's "event_id" value
 * @method gzip               getDescription() Returns the current record's "description" value
 * @method agEvent            getAgEvent()     Returns the current record's "agEvent" value
 * @method agEventDescription setId()          Sets the current record's "id" value
 * @method agEventDescription setEventId()     Sets the current record's "event_id" value
 * @method agEventDescription setDescription() Sets the current record's "description" value
 * @method agEventDescription setAgEvent()     Sets the current record's "agEvent" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagEventDescription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_event_description');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('description', 'gzip', null, array(
             'type' => 'gzip',
             'notnull' => true,
             ));


        $this->index('agEvent_details_unq', array(
             'fields' => 
             array(
              0 => 'event_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agEvent', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}