<?php

/**
 * BaseagEventMessageTrigger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $message_trigger_id
 * @property integer $batch_template_id
 * @property agEvent $agEvent
 * @property agBatchTemplate $agBatchTemplate
 * @property agMessageTrigger $agMessageTrigger
 * 
 * @method integer               getId()                 Returns the current record's "id" value
 * @method integer               getEventId()            Returns the current record's "event_id" value
 * @method integer               getMessageTriggerId()   Returns the current record's "message_trigger_id" value
 * @method integer               getBatchTemplateId()    Returns the current record's "batch_template_id" value
 * @method agEvent               getAgEvent()            Returns the current record's "agEvent" value
 * @method agBatchTemplate       getAgBatchTemplate()    Returns the current record's "agBatchTemplate" value
 * @method agMessageTrigger      getAgMessageTrigger()   Returns the current record's "agMessageTrigger" value
 * @method agEventMessageTrigger setId()                 Sets the current record's "id" value
 * @method agEventMessageTrigger setEventId()            Sets the current record's "event_id" value
 * @method agEventMessageTrigger setMessageTriggerId()   Sets the current record's "message_trigger_id" value
 * @method agEventMessageTrigger setBatchTemplateId()    Sets the current record's "batch_template_id" value
 * @method agEventMessageTrigger setAgEvent()            Sets the current record's "agEvent" value
 * @method agEventMessageTrigger setAgBatchTemplate()    Sets the current record's "agBatchTemplate" value
 * @method agEventMessageTrigger setAgMessageTrigger()   Sets the current record's "agMessageTrigger" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagEventMessageTrigger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_event_message_trigger');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('message_trigger_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('batch_template_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('UX_agEventMessageTrigger', array(
             'fields' => 
             array(
              0 => 'event_id',
              1 => 'message_trigger_id',
              2 => 'batch_template_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agEvent', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('agBatchTemplate', array(
             'local' => 'batch_template_id',
             'foreign' => 'id'));

        $this->hasOne('agMessageTrigger', array(
             'local' => 'message_trigger_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}