<?php

/**
 * BaseagPhoneContactType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $phone_contact_type
 * @property boolean $app_display
 * @property Doctrine_Collection $agPhoneContact
 * @property Doctrine_Collection $agEntityPhoneContact
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getPhoneContactType()     Returns the current record's "phone_contact_type" value
 * @method boolean             getAppDisplay()           Returns the current record's "app_display" value
 * @method Doctrine_Collection getAgPhoneContact()       Returns the current record's "agPhoneContact" collection
 * @method Doctrine_Collection getAgEntityPhoneContact() Returns the current record's "agEntityPhoneContact" collection
 * @method agPhoneContactType  setId()                   Sets the current record's "id" value
 * @method agPhoneContactType  setPhoneContactType()     Sets the current record's "phone_contact_type" value
 * @method agPhoneContactType  setAppDisplay()           Sets the current record's "app_display" value
 * @method agPhoneContactType  setAgPhoneContact()       Sets the current record's "agPhoneContact" collection
 * @method agPhoneContactType  setAgEntityPhoneContact() Sets the current record's "agEntityPhoneContact" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagPhoneContactType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_phone_contact_type');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('phone_contact_type', 'string', 32, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('app_display', 'boolean', null, array(
             'default' => 1,
             'type' => 'boolean',
             'notnull' => true,
             ));


        $this->index('agPhoneContactType_unq', array(
             'fields' => 
             array(
              0 => 'phone_contact_type',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agPhoneContact', array(
             'refClass' => 'agEntityPhoneContact',
             'local' => 'phone_contact_type_id',
             'foreign' => 'phone_contact_id'));

        $this->hasMany('agEntityPhoneContact', array(
             'local' => 'id',
             'foreign' => 'phone_contact_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}