<?php

/**
 * BaseagEntityEmailContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property integer $email_contact_id
 * @property integer $email_contact_type_id
 * @property integer $priority
 * @property agEmailContact $agEmailContact
 * @property agEmailContactType $agEmailContactType
 * @property agEntity $agEntity
 * 
 * @method integer              getId()                    Returns the current record's "id" value
 * @method integer              getEntityId()              Returns the current record's "entity_id" value
 * @method integer              getEmailContactId()        Returns the current record's "email_contact_id" value
 * @method integer              getEmailContactTypeId()    Returns the current record's "email_contact_type_id" value
 * @method integer              getPriority()              Returns the current record's "priority" value
 * @method agEmailContact       getAgEmailContact()        Returns the current record's "agEmailContact" value
 * @method agEmailContactType   getAgEmailContactType()    Returns the current record's "agEmailContactType" value
 * @method agEntity             getAgEntity()              Returns the current record's "agEntity" value
 * @method agEntityEmailContact setId()                    Sets the current record's "id" value
 * @method agEntityEmailContact setEntityId()              Sets the current record's "entity_id" value
 * @method agEntityEmailContact setEmailContactId()        Sets the current record's "email_contact_id" value
 * @method agEntityEmailContact setEmailContactTypeId()    Sets the current record's "email_contact_type_id" value
 * @method agEntityEmailContact setPriority()              Sets the current record's "priority" value
 * @method agEntityEmailContact setAgEmailContact()        Sets the current record's "agEmailContact" value
 * @method agEntityEmailContact setAgEmailContactType()    Sets the current record's "agEmailContactType" value
 * @method agEntityEmailContact setAgEntity()              Sets the current record's "agEntity" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagEntityEmailContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_entity_email_contact');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('entity_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('email_contact_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('email_contact_type_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('priority', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));


        $this->index('agEntityEmailContact_unq', array(
             'fields' => 
             array(
              0 => 'entity_id',
              1 => 'email_contact_id',
              2 => 'email_contact_type_id',
             ),
             'type' => 'unique',
             ));
        $this->index('agEntityAgEmailContact_priority_unq', array(
             'fields' => 
             array(
              0 => 'entity_id',
              1 => 'priority',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agEmailContact', array(
             'local' => 'email_contact_id',
             'foreign' => 'id'));

        $this->hasOne('agEmailContactType', array(
             'local' => 'email_contact_type_id',
             'foreign' => 'id'));

        $this->hasOne('agEntity', array(
             'local' => 'entity_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}