<?php

/**
 * BaseagLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $language
 * @property boolean $app_display
 * @property Doctrine_Collection $agPerson
 * @property Doctrine_Collection $agPersonMjAgLanguage
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getLanguage()             Returns the current record's "language" value
 * @method boolean             getAppDisplay()           Returns the current record's "app_display" value
 * @method Doctrine_Collection getAgPerson()             Returns the current record's "agPerson" collection
 * @method Doctrine_Collection getAgPersonMjAgLanguage() Returns the current record's "agPersonMjAgLanguage" collection
 * @method agLanguage          setId()                   Sets the current record's "id" value
 * @method agLanguage          setLanguage()             Sets the current record's "language" value
 * @method agLanguage          setAppDisplay()           Sets the current record's "app_display" value
 * @method agLanguage          setAgPerson()             Sets the current record's "agPerson" collection
 * @method agLanguage          setAgPersonMjAgLanguage() Sets the current record's "agPersonMjAgLanguage" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_language');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('language', 'string', 128, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('app_display', 'boolean', null, array(
             'default' => 1,
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agPerson', array(
             'refClass' => 'agPersonMjAgLanguage',
             'local' => 'language_id',
             'foreign' => 'person_id'));

        $this->hasMany('agPersonMjAgLanguage', array(
             'local' => 'id',
             'foreign' => 'language_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}