<?php

/**
 * BaseagCustomFieldType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $custom_field_type
 * @property string $description
 * @property boolean $app_display
 * @property Doctrine_Collection $agPersoncustomField
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getCustomFieldType()     Returns the current record's "custom_field_type" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method boolean             getAppDisplay()          Returns the current record's "app_display" value
 * @method Doctrine_Collection getAgPersoncustomField() Returns the current record's "agPersoncustomField" collection
 * @method agCustomFieldType   setId()                  Sets the current record's "id" value
 * @method agCustomFieldType   setCustomFieldType()     Sets the current record's "custom_field_type" value
 * @method agCustomFieldType   setDescription()         Sets the current record's "description" value
 * @method agCustomFieldType   setAppDisplay()          Sets the current record's "app_display" value
 * @method agCustomFieldType   setAgPersoncustomField() Sets the current record's "agPersoncustomField" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagCustomFieldType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_custom_field_type');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('custom_field_type', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('app_display', 'boolean', null, array(
             'default' => 1,
             'type' => 'boolean',
             'notnull' => true,
             ));


        $this->index('agCustomFieldType_unq', array(
             'fields' => 
             array(
              0 => 'custom_field_type',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agPersonCustomField as agPersoncustomField', array(
             'local' => 'id',
             'foreign' => 'custom_field_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}