<?php

/**
 * BaseagPetAllocationStatusType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pet_allocation_status_type
 * @property string $pet_allocation_status_type_desc
 * @property boolean $being_serviced
 * @property Doctrine_Collection $agPetAllocationStatus
 * 
 * @method integer                   getId()                              Returns the current record's "id" value
 * @method string                    getPetAllocationStatusType()         Returns the current record's "pet_allocation_status_type" value
 * @method string                    getPetAllocationStatusTypeDesc()     Returns the current record's "pet_allocation_status_type_desc" value
 * @method boolean                   getBeingServiced()                   Returns the current record's "being_serviced" value
 * @method Doctrine_Collection       getAgPetAllocationStatus()           Returns the current record's "agPetAllocationStatus" collection
 * @method agPetAllocationStatusType setId()                              Sets the current record's "id" value
 * @method agPetAllocationStatusType setPetAllocationStatusType()         Sets the current record's "pet_allocation_status_type" value
 * @method agPetAllocationStatusType setPetAllocationStatusTypeDesc()     Sets the current record's "pet_allocation_status_type_desc" value
 * @method agPetAllocationStatusType setBeingServiced()                   Sets the current record's "being_serviced" value
 * @method agPetAllocationStatusType setAgPetAllocationStatus()           Sets the current record's "agPetAllocationStatus" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagPetAllocationStatusType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_pet_allocation_status_type');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('pet_allocation_status_type', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('pet_allocation_status_type_desc', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('being_serviced', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));


        $this->index('UX_agPetAllocationStatusType', array(
             'fields' => 
             array(
              0 => 'pet_allocation_status_type',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agPetAllocationStatus', array(
             'local' => 'id',
             'foreign' => 'pet_allocation_status_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}