<?php

/**
 * BaseagPersonDateOfBirth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $person_id
 * @property date $date_of_birth
 * @property agPerson $agPerson
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getPersonId()      Returns the current record's "person_id" value
 * @method date                getDateOfBirth()   Returns the current record's "date_of_birth" value
 * @method agPerson            getAgPerson()      Returns the current record's "agPerson" value
 * @method agPersonDateOfBirth setId()            Sets the current record's "id" value
 * @method agPersonDateOfBirth setPersonId()      Sets the current record's "person_id" value
 * @method agPersonDateOfBirth setDateOfBirth()   Sets the current record's "date_of_birth" value
 * @method agPersonDateOfBirth setAgPerson()      Sets the current record's "agPerson" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagPersonDateOfBirth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_person_date_of_birth');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('person_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('date_of_birth', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));


        $this->index('UX_agPersonDateOfBirth', array(
             'fields' => 
             array(
              0 => 'person_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agPerson', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}