<?php

/**
 * BaseagAffectedArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $affected_area
 * @property integer $geo_id
 * @property boolean $required_evacuation
 * @property agGeo $agGeo
 * @property Doctrine_Collection $agEvent
 * @property Doctrine_Collection $agEventAffectedArea
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getAffectedArea()        Returns the current record's "affected_area" value
 * @method integer             getGeoId()               Returns the current record's "geo_id" value
 * @method boolean             getRequiredEvacuation()  Returns the current record's "required_evacuation" value
 * @method agGeo               getAgGeo()               Returns the current record's "agGeo" value
 * @method Doctrine_Collection getAgEvent()             Returns the current record's "agEvent" collection
 * @method Doctrine_Collection getAgEventAffectedArea() Returns the current record's "agEventAffectedArea" collection
 * @method agAffectedArea      setId()                  Sets the current record's "id" value
 * @method agAffectedArea      setAffectedArea()        Sets the current record's "affected_area" value
 * @method agAffectedArea      setGeoId()               Sets the current record's "geo_id" value
 * @method agAffectedArea      setRequiredEvacuation()  Sets the current record's "required_evacuation" value
 * @method agAffectedArea      setAgGeo()               Sets the current record's "agGeo" value
 * @method agAffectedArea      setAgEvent()             Sets the current record's "agEvent" collection
 * @method agAffectedArea      setAgEventAffectedArea() Sets the current record's "agEventAffectedArea" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagAffectedArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_affected_area');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('affected_area', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('geo_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('required_evacuation', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));


        $this->index('agAffectedArea_unq', array(
             'fields' => 
             array(
              0 => 'affected_area',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agGeo', array(
             'local' => 'geo_id',
             'foreign' => 'id'));

        $this->hasMany('agEvent', array(
             'refClass' => 'agEventAffectedArea',
             'local' => 'affected_area_id',
             'foreign' => 'event_id'));

        $this->hasMany('agEventAffectedArea', array(
             'local' => 'id',
             'foreign' => 'affected_area_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}