<?php

/**
 * BaseagScenarioStaffResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $scenario_id
 * @property integer $staff_resource_id
 * @property integer $deployment_weight
 * @property agStaffResource $agStaffResource
 * @property agScenario $agScenario
 * 
 * @method integer                 getId()                Returns the current record's "id" value
 * @method integer                 getScenarioId()        Returns the current record's "scenario_id" value
 * @method integer                 getStaffResourceId()   Returns the current record's "staff_resource_id" value
 * @method integer                 getDeploymentWeight()  Returns the current record's "deployment_weight" value
 * @method agStaffResource         getAgStaffResource()   Returns the current record's "agStaffResource" value
 * @method agScenario              getAgScenario()        Returns the current record's "agScenario" value
 * @method agScenarioStaffResource setId()                Sets the current record's "id" value
 * @method agScenarioStaffResource setScenarioId()        Sets the current record's "scenario_id" value
 * @method agScenarioStaffResource setStaffResourceId()   Sets the current record's "staff_resource_id" value
 * @method agScenarioStaffResource setDeploymentWeight()  Sets the current record's "deployment_weight" value
 * @method agScenarioStaffResource setAgStaffResource()   Sets the current record's "agStaffResource" value
 * @method agScenarioStaffResource setAgScenario()        Sets the current record's "agScenario" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagScenarioStaffResource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_scenario_staff_resource');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('scenario_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('staff_resource_id', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('deployment_weight', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));


        $this->index('UX_agScenarioStaffResource', array(
             'fields' => 
             array(
              0 => 'scenario_id',
              1 => 'staff_resource_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agStaffResource', array(
             'local' => 'staff_resource_id',
             'foreign' => 'id'));

        $this->hasOne('agScenario', array(
             'local' => 'scenario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}