<?php

/**
 * BaseagDefaultMessageBatchTrigger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $message_trigger_id
 * @property integer $message_batch_template_id
 * @property agMessageTrigger $agMessageTrigger
 * @property agMessageBatchTemplate $agMessageBatchTemplate
 * 
 * @method integer                      getId()                        Returns the current record's "id" value
 * @method integer                      getMessageTriggerId()          Returns the current record's "message_trigger_id" value
 * @method integer                      getMessageBatchTemplateId()    Returns the current record's "message_batch_template_id" value
 * @method agMessageTrigger             getAgMessageTrigger()          Returns the current record's "agMessageTrigger" value
 * @method agMessageBatchTemplate       getAgMessageBatchTemplate()    Returns the current record's "agMessageBatchTemplate" value
 * @method agDefaultMessageBatchTrigger setId()                        Sets the current record's "id" value
 * @method agDefaultMessageBatchTrigger setMessageTriggerId()          Sets the current record's "message_trigger_id" value
 * @method agDefaultMessageBatchTrigger setMessageBatchTemplateId()    Sets the current record's "message_batch_template_id" value
 * @method agDefaultMessageBatchTrigger setAgMessageTrigger()          Sets the current record's "agMessageTrigger" value
 * @method agDefaultMessageBatchTrigger setAgMessageBatchTemplate()    Sets the current record's "agMessageBatchTemplate" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagDefaultMessageBatchTrigger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_default_message_batch_trigger');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('message_trigger_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('message_batch_template_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('UX_agDefaultMessageBatchTrigger', array(
             'fields' => 
             array(
              0 => 'message_trigger_id',
              1 => 'message_batch_template_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agMessageTrigger', array(
             'local' => 'message_trigger_id',
             'foreign' => 'id'));

        $this->hasOne('agMessageBatchTemplate', array(
             'local' => 'message_batch_template_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}