<?php

/**
 * BaseagScenarioStaffGenerator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $scenario_id
 * @property integer $search_id
 * @property integer $search_weight
 * @property agScenario $agScenario
 * @property agSearch $agSearch
 * 
 * @method integer                  getId()            Returns the current record's "id" value
 * @method integer                  getScenarioId()    Returns the current record's "scenario_id" value
 * @method integer                  getSearchId()      Returns the current record's "search_id" value
 * @method integer                  getSearchWeight()  Returns the current record's "search_weight" value
 * @method agScenario               getAgScenario()    Returns the current record's "agScenario" value
 * @method agSearch                 getAgSearch()      Returns the current record's "agSearch" value
 * @method agScenarioStaffGenerator setId()            Sets the current record's "id" value
 * @method agScenarioStaffGenerator setScenarioId()    Sets the current record's "scenario_id" value
 * @method agScenarioStaffGenerator setSearchId()      Sets the current record's "search_id" value
 * @method agScenarioStaffGenerator setSearchWeight()  Sets the current record's "search_weight" value
 * @method agScenarioStaffGenerator setAgScenario()    Sets the current record's "agScenario" value
 * @method agScenarioStaffGenerator setAgSearch()      Sets the current record's "agSearch" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagScenarioStaffGenerator extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_scenario_staff_generator');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('scenario_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('search_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('search_weight', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));


        $this->index('agDeploymentSearch_unq', array(
             'fields' => 
             array(
              0 => 'scenario_id',
              1 => 'search_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agScenario', array(
             'local' => 'scenario_id',
             'foreign' => 'id'));

        $this->hasOne('agSearch', array(
             'local' => 'search_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}