<?php

/**
 * BaseagAddressMjAgAddressValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $address_id
 * @property integer $address_value_id
 * @property agAddress $agAddress
 * @property agAddressValue $agAddressValue
 * 
 * @method integer                   getId()               Returns the current record's "id" value
 * @method integer                   getAddressId()        Returns the current record's "address_id" value
 * @method integer                   getAddressValueId()   Returns the current record's "address_value_id" value
 * @method agAddress                 getAgAddress()        Returns the current record's "agAddress" value
 * @method agAddressValue            getAgAddressValue()   Returns the current record's "agAddressValue" value
 * @method agAddressMjAgAddressValue setId()               Sets the current record's "id" value
 * @method agAddressMjAgAddressValue setAddressId()        Sets the current record's "address_id" value
 * @method agAddressMjAgAddressValue setAddressValueId()   Sets the current record's "address_value_id" value
 * @method agAddressMjAgAddressValue setAgAddress()        Sets the current record's "agAddress" value
 * @method agAddressMjAgAddressValue setAgAddressValue()   Sets the current record's "agAddressValue" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagAddressMjAgAddressValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_address_mj_ag_address_value');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('address_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('address_value_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));


        $this->index('agAddressMjAgAddressValue_unq', array(
             'fields' => 
             array(
              0 => 'address_id',
              1 => 'address_value_id',
             ),
             'type' => 'unique',
             ));
        $this->index('agAddressMjAgAddressValue_addressId', array(
             'fields' => 
             array(
              0 => 'address_id',
             ),
             ));
        $this->index('agAddressMjAgAddressValue_addressValueId', array(
             'fields' => 
             array(
              0 => 'address_value_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agAddress', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasOne('agAddressValue', array(
             'local' => 'address_value_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}