<?php

/**
 * BaseagCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $country
 * @property boolean $app_display
 * @property Doctrine_Collection $agPhoneFormat
 * @property Doctrine_Collection $agPerson
 * @property Doctrine_Collection $agResidentialStatus
 * @property Doctrine_Collection $agPersonResidentialStatus
 * @property Doctrine_Collection $agAddressStandard
 * @property Doctrine_Collection $agIso31662
 * @property Doctrine_Collection $agIso31661Alpha2
 * @property Doctrine_Collection $agIso31661Alpha3
 * @property Doctrine_Collection $agIso31661Numeric
 * @property Doctrine_Collection $agCountryMjAgIso31662
 * @property Doctrine_Collection $agCountryMjAgIso31661Alpha2
 * @property Doctrine_Collection $agCountryMjAgIso31661Alpha3
 * @property Doctrine_Collection $agCountryMjAgIso31661Numeric
 * 
 * @method integer             getId()                           Returns the current record's "id" value
 * @method string              getCountry()                      Returns the current record's "country" value
 * @method boolean             getAppDisplay()                   Returns the current record's "app_display" value
 * @method Doctrine_Collection getAgPhoneFormat()                Returns the current record's "agPhoneFormat" collection
 * @method Doctrine_Collection getAgPerson()                     Returns the current record's "agPerson" collection
 * @method Doctrine_Collection getAgResidentialStatus()          Returns the current record's "agResidentialStatus" collection
 * @method Doctrine_Collection getAgPersonResidentialStatus()    Returns the current record's "agPersonResidentialStatus" collection
 * @method Doctrine_Collection getAgAddressStandard()            Returns the current record's "agAddressStandard" collection
 * @method Doctrine_Collection getAgIso31662()                   Returns the current record's "agIso31662" collection
 * @method Doctrine_Collection getAgIso31661Alpha2()             Returns the current record's "agIso31661Alpha2" collection
 * @method Doctrine_Collection getAgIso31661Alpha3()             Returns the current record's "agIso31661Alpha3" collection
 * @method Doctrine_Collection getAgIso31661Numeric()            Returns the current record's "agIso31661Numeric" collection
 * @method Doctrine_Collection getAgCountryMjAgIso31662()        Returns the current record's "agCountryMjAgIso31662" collection
 * @method Doctrine_Collection getAgCountryMjAgIso31661Alpha2()  Returns the current record's "agCountryMjAgIso31661Alpha2" collection
 * @method Doctrine_Collection getAgCountryMjAgIso31661Alpha3()  Returns the current record's "agCountryMjAgIso31661Alpha3" collection
 * @method Doctrine_Collection getAgCountryMjAgIso31661Numeric() Returns the current record's "agCountryMjAgIso31661Numeric" collection
 * @method agCountry           setId()                           Sets the current record's "id" value
 * @method agCountry           setCountry()                      Sets the current record's "country" value
 * @method agCountry           setAppDisplay()                   Sets the current record's "app_display" value
 * @method agCountry           setAgPhoneFormat()                Sets the current record's "agPhoneFormat" collection
 * @method agCountry           setAgPerson()                     Sets the current record's "agPerson" collection
 * @method agCountry           setAgResidentialStatus()          Sets the current record's "agResidentialStatus" collection
 * @method agCountry           setAgPersonResidentialStatus()    Sets the current record's "agPersonResidentialStatus" collection
 * @method agCountry           setAgAddressStandard()            Sets the current record's "agAddressStandard" collection
 * @method agCountry           setAgIso31662()                   Sets the current record's "agIso31662" collection
 * @method agCountry           setAgIso31661Alpha2()             Sets the current record's "agIso31661Alpha2" collection
 * @method agCountry           setAgIso31661Alpha3()             Sets the current record's "agIso31661Alpha3" collection
 * @method agCountry           setAgIso31661Numeric()            Sets the current record's "agIso31661Numeric" collection
 * @method agCountry           setAgCountryMjAgIso31662()        Sets the current record's "agCountryMjAgIso31662" collection
 * @method agCountry           setAgCountryMjAgIso31661Alpha2()  Sets the current record's "agCountryMjAgIso31661Alpha2" collection
 * @method agCountry           setAgCountryMjAgIso31661Alpha3()  Sets the current record's "agCountryMjAgIso31661Alpha3" collection
 * @method agCountry           setAgCountryMjAgIso31661Numeric() Sets the current record's "agCountryMjAgIso31661Numeric" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_country');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('country', 'string', 128, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('app_display', 'boolean', null, array(
             'default' => 1,
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agPhoneFormat', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('agPerson', array(
             'refClass' => 'agPersonResidentialStatus',
             'local' => 'country_id',
             'foreign' => 'person_id'));

        $this->hasMany('agResidentialStatus', array(
             'refClass' => 'agPersonResidentialStatus',
             'local' => 'country_id',
             'foreign' => 'residential_status_id'));

        $this->hasMany('agPersonResidentialStatus', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('agAddressStandard', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('agIso31662', array(
             'refClass' => 'agCountryMjAgIso31662',
             'local' => 'country_id',
             'foreign' => 'iso_31662_id'));

        $this->hasMany('agIso31661Alpha2', array(
             'refClass' => 'agCountryMjAgIso31661Alpha2',
             'local' => 'country_id',
             'foreign' => 'iso_31661_alpha2_id'));

        $this->hasMany('agIso31661Alpha3', array(
             'refClass' => 'agCountryMjAgIso31661Alpha3',
             'local' => 'country_id',
             'foreign' => 'iso_31661_alpha3_id'));

        $this->hasMany('agIso31661Numeric', array(
             'refClass' => 'agCountryMjAgIso31661Numeric',
             'local' => 'country_id',
             'foreign' => 'iso_31661_numeric_id'));

        $this->hasMany('agCountryMjAgIso31662', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('agCountryMjAgIso31661Alpha2', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('agCountryMjAgIso31661Alpha3', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('agCountryMjAgIso31661Numeric', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}