<?php

/**
 * BasetempFacilityImport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $facility_name
 * @property string $facility_code
 * @property string $facility_resource_type_abbr
 * @property string $facility_resource_status
 * @property integer $facility_capacity
 * @property integer $facility_activation_sequece
 * @property string $facility_allocation_status
 * @property string $facility_group
 * @property string $facility_group_allocation_status
 * @property integer $faciltiy_group_activation_sequence
 * @property string $work_email
 * @property string $work_phone
 * @property string $street_1
 * @property string $street_2
 * @property string $city
 * @property string $state
 * @property string $zip_code
 * @property string $borough
 * @property string $country
 * @property decimal $longitude
 * @property decimal $latitude
 * @property integer $generalist_min
 * @property integer $generalist_max
 * @property integer $specialist_min
 * @property integer $specialist_max
 * @property integer $operator_min
 * @property integer $operator_max
 * @property integer $medical_nurse_min
 * @property integer $medical_nurse_max
 * @property integer $medical_other_min
 * @property integer $medical_other_max
 * 
 * @method integer            getId()                                 Returns the current record's "id" value
 * @method string             getFacilityName()                       Returns the current record's "facility_name" value
 * @method string             getFacilityCode()                       Returns the current record's "facility_code" value
 * @method string             getFacilityResourceTypeAbbr()           Returns the current record's "facility_resource_type_abbr" value
 * @method string             getFacilityResourceStatus()             Returns the current record's "facility_resource_status" value
 * @method integer            getFacilityCapacity()                   Returns the current record's "facility_capacity" value
 * @method integer            getFacilityActivationSequece()          Returns the current record's "facility_activation_sequece" value
 * @method string             getFacilityAllocationStatus()           Returns the current record's "facility_allocation_status" value
 * @method string             getFacilityGroup()                      Returns the current record's "facility_group" value
 * @method string             getFacilityGroupAllocationStatus()      Returns the current record's "facility_group_allocation_status" value
 * @method integer            getFaciltiyGroupActivationSequence()    Returns the current record's "faciltiy_group_activation_sequence" value
 * @method string             getWorkEmail()                          Returns the current record's "work_email" value
 * @method string             getWorkPhone()                          Returns the current record's "work_phone" value
 * @method string             getStreet1()                            Returns the current record's "street_1" value
 * @method string             getStreet2()                            Returns the current record's "street_2" value
 * @method string             getCity()                               Returns the current record's "city" value
 * @method string             getState()                              Returns the current record's "state" value
 * @method string             getZipCode()                            Returns the current record's "zip_code" value
 * @method string             getBorough()                            Returns the current record's "borough" value
 * @method string             getCountry()                            Returns the current record's "country" value
 * @method decimal            getLongitude()                          Returns the current record's "longitude" value
 * @method decimal            getLatitude()                           Returns the current record's "latitude" value
 * @method integer            getGeneralistMin()                      Returns the current record's "generalist_min" value
 * @method integer            getGeneralistMax()                      Returns the current record's "generalist_max" value
 * @method integer            getSpecialistMin()                      Returns the current record's "specialist_min" value
 * @method integer            getSpecialistMax()                      Returns the current record's "specialist_max" value
 * @method integer            getOperatorMin()                        Returns the current record's "operator_min" value
 * @method integer            getOperatorMax()                        Returns the current record's "operator_max" value
 * @method integer            getMedicalNurseMin()                    Returns the current record's "medical_nurse_min" value
 * @method integer            getMedicalNurseMax()                    Returns the current record's "medical_nurse_max" value
 * @method integer            getMedicalOtherMin()                    Returns the current record's "medical_other_min" value
 * @method integer            getMedicalOtherMax()                    Returns the current record's "medical_other_max" value
 * @method tempFacilityImport setId()                                 Sets the current record's "id" value
 * @method tempFacilityImport setFacilityName()                       Sets the current record's "facility_name" value
 * @method tempFacilityImport setFacilityCode()                       Sets the current record's "facility_code" value
 * @method tempFacilityImport setFacilityResourceTypeAbbr()           Sets the current record's "facility_resource_type_abbr" value
 * @method tempFacilityImport setFacilityResourceStatus()             Sets the current record's "facility_resource_status" value
 * @method tempFacilityImport setFacilityCapacity()                   Sets the current record's "facility_capacity" value
 * @method tempFacilityImport setFacilityActivationSequece()          Sets the current record's "facility_activation_sequece" value
 * @method tempFacilityImport setFacilityAllocationStatus()           Sets the current record's "facility_allocation_status" value
 * @method tempFacilityImport setFacilityGroup()                      Sets the current record's "facility_group" value
 * @method tempFacilityImport setFacilityGroupAllocationStatus()      Sets the current record's "facility_group_allocation_status" value
 * @method tempFacilityImport setFaciltiyGroupActivationSequence()    Sets the current record's "faciltiy_group_activation_sequence" value
 * @method tempFacilityImport setWorkEmail()                          Sets the current record's "work_email" value
 * @method tempFacilityImport setWorkPhone()                          Sets the current record's "work_phone" value
 * @method tempFacilityImport setStreet1()                            Sets the current record's "street_1" value
 * @method tempFacilityImport setStreet2()                            Sets the current record's "street_2" value
 * @method tempFacilityImport setCity()                               Sets the current record's "city" value
 * @method tempFacilityImport setState()                              Sets the current record's "state" value
 * @method tempFacilityImport setZipCode()                            Sets the current record's "zip_code" value
 * @method tempFacilityImport setBorough()                            Sets the current record's "borough" value
 * @method tempFacilityImport setCountry()                            Sets the current record's "country" value
 * @method tempFacilityImport setLongitude()                          Sets the current record's "longitude" value
 * @method tempFacilityImport setLatitude()                           Sets the current record's "latitude" value
 * @method tempFacilityImport setGeneralistMin()                      Sets the current record's "generalist_min" value
 * @method tempFacilityImport setGeneralistMax()                      Sets the current record's "generalist_max" value
 * @method tempFacilityImport setSpecialistMin()                      Sets the current record's "specialist_min" value
 * @method tempFacilityImport setSpecialistMax()                      Sets the current record's "specialist_max" value
 * @method tempFacilityImport setOperatorMin()                        Sets the current record's "operator_min" value
 * @method tempFacilityImport setOperatorMax()                        Sets the current record's "operator_max" value
 * @method tempFacilityImport setMedicalNurseMin()                    Sets the current record's "medical_nurse_min" value
 * @method tempFacilityImport setMedicalNurseMax()                    Sets the current record's "medical_nurse_max" value
 * @method tempFacilityImport setMedicalOtherMin()                    Sets the current record's "medical_other_min" value
 * @method tempFacilityImport setMedicalOtherMax()                    Sets the current record's "medical_other_max" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetempFacilityImport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('temp_facility_import');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('facility_name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('facility_code', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('facility_resource_type_abbr', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('facility_resource_status', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('facility_capacity', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('facility_activation_sequece', 'integer', 1, array(
             'unsigned' => true,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('facility_allocation_status', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('facility_group', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('facility_group_allocation_status', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('faciltiy_group_activation_sequence', 'integer', 1, array(
             'unsigned' => true,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('work_email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('work_phone', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('street_1', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('street_2', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('city', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('state', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('zip_code', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('borough', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('country', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('longitude', 'decimal', 12, array(
             'scale' => 6,
             'type' => 'decimal',
             'length' => 12,
             ));
        $this->hasColumn('latitude', 'decimal', 12, array(
             'scale' => 6,
             'type' => 'decimal',
             'length' => 12,
             ));
        $this->hasColumn('generalist_min', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('generalist_max', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('specialist_min', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('specialist_max', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('operator_min', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('operator_max', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('medical_nurse_min', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('medical_nurse_max', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('medical_other_min', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('medical_other_max', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}