<?php

/**
 * BaseagAccountStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $account_status
 * @property Doctrine_Collection $agAccount
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getAccountStatus()  Returns the current record's "account_status" value
 * @method Doctrine_Collection getAgAccount()      Returns the current record's "agAccount" collection
 * @method agAccountStatus     setId()             Sets the current record's "id" value
 * @method agAccountStatus     setAccountStatus()  Sets the current record's "account_status" value
 * @method agAccountStatus     setAgAccount()      Sets the current record's "agAccount" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagAccountStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_account_status');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('account_status', 'string', 30, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agAccount', array(
             'local' => 'id',
             'foreign' => 'account_status_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}