<?php

/**
 * BaseagSubSpecies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $subspecies
 * @property Doctrine_Collection $agPetSubSpecies
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getSubspecies()      Returns the current record's "subspecies" value
 * @method Doctrine_Collection getAgPetSubSpecies() Returns the current record's "agPetSubSpecies" collection
 * @method agSubSpecies        setId()              Sets the current record's "id" value
 * @method agSubSpecies        setSubspecies()      Sets the current record's "subspecies" value
 * @method agSubSpecies        setAgPetSubSpecies() Sets the current record's "agPetSubSpecies" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagSubSpecies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_sub_species');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('subspecies', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));


        $this->index('UX_agSubSpecies', array(
             'fields' => 
             array(
              0 => 'subspecies',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agPetSubSpecies', array(
             'local' => 'id',
             'foreign' => 'subspecies_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}