<?php

/**
 * BaseagPersonLastImport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $person_id
 * @property integer $last_import_id
 * @property agPerson $agPerson
 * @property agImport $agImport
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getPersonId()       Returns the current record's "person_id" value
 * @method integer            getLastImportId()   Returns the current record's "last_import_id" value
 * @method agPerson           getAgPerson()       Returns the current record's "agPerson" value
 * @method agImport           getAgImport()       Returns the current record's "agImport" value
 * @method agPersonLastImport setId()             Sets the current record's "id" value
 * @method agPersonLastImport setPersonId()       Sets the current record's "person_id" value
 * @method agPersonLastImport setLastImportId()   Sets the current record's "last_import_id" value
 * @method agPersonLastImport setAgPerson()       Sets the current record's "agPerson" value
 * @method agPersonLastImport setAgImport()       Sets the current record's "agImport" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagPersonLastImport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_person_last_import');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('person_id', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('last_import_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('UX_agPersonLastImport', array(
             'fields' => 
             array(
              0 => 'person_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agPerson', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('agImport', array(
             'local' => 'last_import_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}