<?php

/**
 * BaseagClientGroupComposition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_group_id
 * @property integer $client_group_composition_type_id
 * @property integer $member_count
 * @property agClientGroup $agClientGroup
 * @property agClientGroupCompositionType $agClientGroupCompositionType
 * 
 * @method integer                      getId()                               Returns the current record's "id" value
 * @method integer                      getClientGroupId()                    Returns the current record's "client_group_id" value
 * @method integer                      getClientGroupCompositionTypeId()     Returns the current record's "client_group_composition_type_id" value
 * @method integer                      getMemberCount()                      Returns the current record's "member_count" value
 * @method agClientGroup                getAgClientGroup()                    Returns the current record's "agClientGroup" value
 * @method agClientGroupCompositionType getAgClientGroupCompositionType()     Returns the current record's "agClientGroupCompositionType" value
 * @method agClientGroupComposition     setId()                               Sets the current record's "id" value
 * @method agClientGroupComposition     setClientGroupId()                    Sets the current record's "client_group_id" value
 * @method agClientGroupComposition     setClientGroupCompositionTypeId()     Sets the current record's "client_group_composition_type_id" value
 * @method agClientGroupComposition     setMemberCount()                      Sets the current record's "member_count" value
 * @method agClientGroupComposition     setAgClientGroup()                    Sets the current record's "agClientGroup" value
 * @method agClientGroupComposition     setAgClientGroupCompositionType()     Sets the current record's "agClientGroupCompositionType" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagClientGroupComposition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_client_group_composition');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('client_group_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('client_group_composition_type_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('member_count', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('UX_agClientGroupComposition', array(
             'fields' => 
             array(
              0 => 'client_group_id',
              1 => 'client_group_composition_type_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agClientGroup', array(
             'local' => 'client_group_id',
             'foreign' => 'id'));

        $this->hasOne('agClientGroupCompositionType', array(
             'local' => 'client_group_composition_type_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}