<?php

/**
 * BaseagIso31661Alpha3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $value
 * @property Doctrine_Collection $agCountry
 * @property Doctrine_Collection $agCountryMjAgIso31661Alpha3
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method string              getValue()                       Returns the current record's "value" value
 * @method Doctrine_Collection getAgCountry()                   Returns the current record's "agCountry" collection
 * @method Doctrine_Collection getAgCountryMjAgIso31661Alpha3() Returns the current record's "agCountryMjAgIso31661Alpha3" collection
 * @method agIso31661Alpha3    setId()                          Sets the current record's "id" value
 * @method agIso31661Alpha3    setValue()                       Sets the current record's "value" value
 * @method agIso31661Alpha3    setAgCountry()                   Sets the current record's "agCountry" collection
 * @method agIso31661Alpha3    setAgCountryMjAgIso31661Alpha3() Sets the current record's "agCountryMjAgIso31661Alpha3" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagIso31661Alpha3 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_iso31661_alpha3');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('value', 'string', 3, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agCountry', array(
             'refClass' => 'agCountryMjAgIso31661Alpha3',
             'local' => 'iso_31661_alpha3_id',
             'foreign' => 'country_id'));

        $this->hasMany('agCountryMjAgIso31661Alpha3', array(
             'local' => 'id',
             'foreign' => 'iso_31661_alpha3_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}