<?php

/**
 * BaseagAddressContactType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $address_contact_type
 * @property boolean $app_display
 * @property Doctrine_Collection $agSiteAddress
 * @property Doctrine_Collection $agEntityAddressContact
 * 
 * @method integer              getId()                     Returns the current record's "id" value
 * @method string               getAddressContactType()     Returns the current record's "address_contact_type" value
 * @method boolean              getAppDisplay()             Returns the current record's "app_display" value
 * @method Doctrine_Collection  getAgSiteAddress()          Returns the current record's "agSiteAddress" collection
 * @method Doctrine_Collection  getAgEntityAddressContact() Returns the current record's "agEntityAddressContact" collection
 * @method agAddressContactType setId()                     Sets the current record's "id" value
 * @method agAddressContactType setAddressContactType()     Sets the current record's "address_contact_type" value
 * @method agAddressContactType setAppDisplay()             Sets the current record's "app_display" value
 * @method agAddressContactType setAgSiteAddress()          Sets the current record's "agSiteAddress" collection
 * @method agAddressContactType setAgEntityAddressContact() Sets the current record's "agEntityAddressContact" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagAddressContactType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_address_contact_type');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('address_contact_type', 'string', 32, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('app_display', 'boolean', null, array(
             'default' => 1,
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agAddress as agSiteAddress', array(
             'refClass' => 'agEntityAddressContact',
             'local' => 'address_contact_type_id',
             'foreign' => 'address_id'));

        $this->hasMany('agEntityAddressContact', array(
             'local' => 'id',
             'foreign' => 'address_contact_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}