<?php

/**
 * agAddressGeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agAddressGeoTable extends PluginagAddressGeoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agAddressGeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agAddressGeo');
    }
}