<?php

/**
 * agGeoFeatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agGeoFeatureTable extends PluginagGeoFeatureTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agGeoFeatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agGeoFeature');
    }
}