<?php

/**
 * agGeoTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agGeoTypeTable extends PluginagGeoTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agGeoTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agGeoType');
    }
}