<?php

/**
 * PluginagFooTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginagFooTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginagFooTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginagFoo');
    }
}