<?php

/**
 * PluginagEventFacilityResourceActivationTimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginagEventFacilityResourceActivationTimeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginagEventFacilityResourceActivationTimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginagEventFacilityResourceActivationTime');
    }
}