<?php

/**
 * PluginagEventStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginagEventStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginagEventStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginagEventStatus');
    }
}