<?php

/**
 * PluginagEventFacilityGroupStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginagEventFacilityGroupStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginagEventFacilityGroupStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginagEventFacilityGroupStatus');
    }
}