<?php

/**
 * PluginagEventFacilityGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginagEventFacilityGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginagEventFacilityGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginagEventFacilityGroup');
    }
}