<?php

/**
 * PluginagEventServiceAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginagEventServiceAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginagEventServiceAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginagEventServiceArea');
    }
}