<?php

/**
 * PluginagEventDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginagEventDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginagEventDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginagEventDescription');
    }
}