<?php

/**
 * PluginagEventStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginagEventStatus extends BaseagEventStatus
{
  /**
   * Method to statically return an event status based on statusTypeId
   * @param integer $eventStatusTypeId An event status type Id
   * @return strin An string representation of event status
   */
  public static function getStatusType($eventStatusTypeId)
  {
    return agDoctrineQuery::create()
      ->select('est.event_status_type')
        ->from('agEventStatusType est')
        ->where('est.id = ?', $eventStatusTypeId)
        ->useResultCache(TRUE, 3600)
        ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);

  }
}