<?php

/**
 * agFacilityResourceType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class agFacilityResourceType extends BaseagFacilityResourceType
{
    public $luceneSearchFields = array
    (
    'facility_resource' => 'unstored'
    );

  public function updateLucene()
  {
    $doc = new Zend_Search_Lucene_Document();
    $doc->addField(Zend_Search_Lucene_Field::unStored('facility_resource', $this->faciltiy_resource_type . ' ' . $this->faciltiy_resource_type_abbr, 'utf-8'));

  return $doc;
  }

}
