<?php

/** 
* Contains the BaseagPersonMjAgPersonName class
*
* PHP Version 5
*
* LICENSE: This source file is subject to LGPLv3.0 license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author Ilya Gulko, CUNY SPS
*
* Copyright of the Sahana Software Foundation, sahanafoundation.org
*/

/**
* agPersonMjAgPersonName is an extension of BaseagPersonMjAgPersonName that allows for
 * additional functionality to added to the class without directly modifying the
 * agPersonMjAgPersonName model generated by Doctrine.
*/
class agPersonMjAgPersonName extends BaseagPersonMjAgPersonName
{
}
