<?php

/**
 * agAccountStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agAccountStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agAccountStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agAccountStatus');
    }
}