<?php

/**
 * agAccountMjSfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agAccountMjSfGuardUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agAccountMjSfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agAccountMjSfGuardUser');
    }
}