<?php

/**
 * agAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agAccount');
    }
}