<?php

/**
 * agAddressFormatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agAddressFormatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agAddressFormatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agAddressFormat');
    }
}