<?php

/**
 * agBatchTemplateReplyArgumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agBatchTemplateReplyArgumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agBatchTemplateReplyArgumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agBatchTemplateReplyArgument');
    }
}