<?php

/**
 * agBranchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agBranchTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agBranchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agBranch');
    }
}