<?php

/**
 * agCertifiedSkillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agCertifiedSkillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agCertifiedSkillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agCertifiedSkill');
    }
}