<?php

/**
 * agClientGroupCompositionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientGroupCompositionTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientGroupCompositionTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientGroupCompositionType');
    }
}