<?php

/**
 * agClientGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientGroupTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientGroup');
    }
}