<?php

/**
 * agClientGroupCompositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientGroupCompositionTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientGroupCompositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientGroupComposition');
    }
}