<?php

/**
 * agClientAllocationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientAllocationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientAllocationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientAllocationStatus');
    }
}