<?php

/**
 * agClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClient');
    }
}