<?php

/**
 * agClientAllocationStatusTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientAllocationStatusTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientAllocationStatusTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientAllocationStatusType');
    }
}