<?php

/**
 * agClientMedicalStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientMedicalStatusTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientMedicalStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientMedicalStatus');
    }
}