<?php

/**
 * agClientAgeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientAgeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientAgeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientAge');
    }
}