<?php

/**
 * agClientMedicalStatusTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agClientMedicalStatusTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agClientMedicalStatusTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agClientMedicalStatusType');
    }
}