<?php

/**
 * agCountryMjAgIso31662Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agCountryMjAgIso31662Table extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agCountryMjAgIso31662Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agCountryMjAgIso31662');
    }
}