<?php

/**
 * agCountryMjAgIso31661Alpha2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class agCountryMjAgIso31661Alpha2 extends BaseagCountryMjAgIso31661Alpha2
{
}
