<?php

/**
 * agCustomFieldTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agCustomFieldTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agCustomFieldTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agCustomFieldType');
    }
}