<?php

/**
 * agDefaultScenarioFacilityResourceTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agDefaultScenarioFacilityResourceTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agDefaultScenarioFacilityResourceTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agDefaultScenarioFacilityResourceType');
    }
}