<?php

/**
 * agEmailContactTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEmailContactTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEmailContactTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEmailContactType');
    }
}