<?php

/**
 * agEntityAddressContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEntityAddressContactTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEntityAddressContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEntityAddressContact');
    }
}