<?php

/**
 * agEntityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEntityTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEntityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEntity');
    }
}