<?php

/**
 * agEntityPhoneContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEntityPhoneContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEntityPhoneContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEntityPhoneContact');
    }
}