<?php

/**
 * agEthnicityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEthnicityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEthnicityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEthnicity');
    }
}