<?php

/**
 * agEventFacilityResourceActivationTimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventFacilityResourceActivationTimeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventFacilityResourceActivationTimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventFacilityResourceActivationTime');
    }
}