<?php

/**
 * agEventAuditValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventAuditValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventAuditValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventAuditValue');
    }
}