<?php

/**
 * agEventFacilityDistributionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventFacilityDistributionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventFacilityDistributionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventFacilityDistribution');
    }
}