<?php

/**
 * agFacilityGroupTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agFacilityGroupTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agFacilityGroupTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agFacilityGroupType');
    }
}