<?php

/**
 * agFacilityResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agFacilityResourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agFacilityResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agFacilityResource');
    }
}