<?php

/**
 * agFacilityResourceTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agFacilityResourceTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agFacilityResourceTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agFacilityResourceType');
    }
}