<?php

/**
 * agFacilityGroupAllocationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agFacilityGroupAllocationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agFacilityGroupAllocationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agFacilityGroupAllocationStatus');
    }
}