<?php

/**
 * agGlobalParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agGlobalParamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agGlobalParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agGlobalParam');
    }
}