<?php

/**
 * agHostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agHostTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agHostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agHost');
    }
}