<?php

/**
 * agIso31661Alpha3Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agIso31661Alpha3Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agIso31661Alpha3Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agIso31661Alpha3');
    }
}