<?php

/**
 * agIso31661Alpha2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agIso31661Alpha2Table extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agIso31661Alpha2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agIso31661Alpha2');
    }
}