<?php

/**
 * agLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agLanguageTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agLanguage');
    }
}