<?php

/**
 * agLuceneSearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agLuceneSearchTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agLuceneSearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agLuceneSearch');
    }
}