<?php

/**
 * agMaritalStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMaritalStatusTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMaritalStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMaritalStatus');
    }
}