<?php

/**
 * agMessageReplyArgumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMessageReplyArgumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMessageReplyArgumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMessageReplyArgument');
    }
}