<?php

/**
 * agMessageTemplateElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMessageTemplateElementTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMessageTemplateElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMessageTemplateElement');
    }
}