<?php

/**
 * agMessageElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMessageElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMessageElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMessageElement');
    }
}