<?php

/**
 * agMessageBatchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMessageBatchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMessageBatchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMessageBatch');
    }
}