<?php

/**
 * agMessageTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMessageTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMessageTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMessageType');
    }
}