<?php

/**
 * agMessageTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMessageTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMessageTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMessageTemplate');
    }
}