<?php

/**
 * agMessageReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agMessageReplyTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agMessageReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agMessageReply');
    }
}