<?php

/**
 * agNationalityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agNationalityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agNationalityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agNationality');
    }
}