<?php

/**
 * agOrganizationBranchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agOrganizationBranchTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agOrganizationBranchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agOrganizationBranch');
    }
}