<?php

/**
 * agPersonNameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPersonNameTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPersonNameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPersonName');
    }
}