<?php

/**
 * agPersonNameTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPersonNameTypeTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPersonNameTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPersonNameType');
    }
}