<?php

/**
 * agPetCaretakerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPetCaretakerTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPetCaretakerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPetCaretaker');
    }
}