<?php

/**
 * agPersonDateOfBirthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPersonDateOfBirthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPersonDateOfBirthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPersonDateOfBirth');
    }
}