<?php

/**
 * agPetSubSpeciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPetSubSpeciesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPetSubSpeciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPetSubSpecies');
    }
}