<?php

/**
 * agPetAllocationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPetAllocationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPetAllocationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPetAllocationStatus');
    }
}