<?php

/**
 * agPersonCertificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPersonCertificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPersonCertificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPersonCertification');
    }
}