<?php

/**
 * agPersonMjAgProfessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPersonMjAgProfessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPersonMjAgProfessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPersonMjAgProfession');
    }
}