<?php

/**
 * agPersonLanguageCompetencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPersonLanguageCompetencyTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPersonLanguageCompetencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPersonLanguageCompetency');
    }
}