<?php

/**
 * agPersonMaritalStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPersonMaritalStatusTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPersonMaritalStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPersonMaritalStatus');
    }
}