<?php

/**
 * agPhoneContactTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPhoneContactTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPhoneContactTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPhoneContactType');
    }
}