<?php

/**
 * agPhoneFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agPhoneFormatTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agPhoneFormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agPhoneFormatType');
    }
}