<?php

/**
 * agRawSkillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agRawSkillTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agRawSkillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agRawSkill');
    }
}