<?php

/**
 * agResidentialStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agResidentialStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agResidentialStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agResidentialStatus');
    }
}