<?php

/**
 * agScenarioShiftTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agScenarioShiftTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agScenarioShiftTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agScenarioShift');
    }
}