<?php

/**
 * agScenarioStaffResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agScenarioStaffResourceTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agScenarioStaffResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agScenarioStaffResource');
    }
}