<?php

/**
 * agScenarioServiceAreaCompositeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agScenarioServiceAreaCompositeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agScenarioServiceAreaCompositeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agScenarioServiceAreaComposite');
    }
}