<?php

/**
 * agScenarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agScenarioTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agScenarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agScenario');
    }
}