<?php

/**
 * agScenarioAffectedAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agScenarioAffectedAreaTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agScenarioAffectedAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agScenarioAffectedArea');
    }
}