<?php

/**
 * agScenarioServiceAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agScenarioServiceAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agScenarioServiceAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agScenarioServiceArea');
    }
}