<?php

/**
 * agSexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agSexTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agSexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agSex');
    }
}