<?php

/**
 * agShiftTemplateMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agShiftTemplateMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agShiftTemplateMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agShiftTemplateMessage');
    }
}