<?php

/**
 * agShiftTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agShiftTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agShiftTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agShiftTemplate');
    }
}