<?php

/**
 * agSpeciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agSpeciesTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agSpeciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agSpecies');
    }
}