<?php

/**
 * agStaffResourceTypeProvisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agStaffResourceTypeProvisionTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agStaffResourceTypeProvisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agStaffResourceTypeProvision');
    }
}