<?php

/**
 * agSubSpeciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agSubSpeciesTable extends agDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agSubSpeciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agSubSpecies');
    }
}