<?php

/**
 * temp_import_migrationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class temp_import_migrationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object temp_import_migrationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('temp_import_migration');
    }
}