# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }
facility:
  url:  /facility
  param: { module: facility, action: index }
staff_index:
  url: /staff
  param: { module: agStaff, action: index }
staff:
  url: /staff/:action
  param: { module: agStaff }
client:
  url: /client
  param: { module: client, action: index }
scenario:
  url: /scenario
  param: { module: scenario, action: index }
org:
  url: /organization
  param: { module: organization, action: index }
gis_index:
  url: /gis
  param: { module: agGis, action: index }
gis:
  url: /gis/:action
  param: { module: agGis}
admin:
  url: /admin
  param: { module: admin, action: index }
about:
  url: /about
  param: { module: about, action: index }
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

scenario_show_facility_staff_resource:
  url:     /scenario/:id/staff_resources
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: showFacilityStaffResource }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
staff_search:
  url:   /staff/search
  param: { module: agStaff, action: search }
staff_filter:
  url:   /staff/filter
  param: { module: agStaff, action: filter }