# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }
facility:
  url:  /facility
  param: { module: facility, action: index }
client:
  url: /client
  param: { module: client, action: index }
scenario:
  url: /scenario
  param: { module: scenario, action: index }
org:
  url: /organization
  param: { module: organization, action: index }
admin:
  url: /admin
  param: { module: admin, action: index }
about:
  url: /about
  param: { module: about, action: index }
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

facility_import:
  url:  /facility/import
  param: { module: facility, action: import }

scenario_show_facility_staff_resource:
  url:     /scenario/:id/staffresources
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: staffresources }

scenario_staff_pool:
  url:     /scenario/:id/staffpool
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: staffpool }

scenario_search:
  url:     /scenario/:id/search
  options: { model: agScenario, type: object }
  param:   { module: scenario, action search }

scenario_fgroup:
  url:     /scenario/:id/fgroup
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: fgroup }

scenario_new_shift_templates:
  url:     /scenario/:id/newshifttemplates
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: newshifttemplates }

scenario_shift_templates:
  url:     /scenario/:id/shifttemplates
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: shifttemplates }

scenario_shift_list:
  url:     /scenario/:id/scenarioshiftlist
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: scenarioshiftlist }

scenario_shifts:
  url:     /scenario/:id/scenarioshifts
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: scenarioshifts }

scenario_review:
  url:     /scenario/:id/review
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: review }

scenario_facility_group:
  url:     /scenario/:id/listgroup
  options: { model: agScenario, type: object }
  param:   { module: scenario, action: listgroup }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
