<?php

/**
 * agStaffResourceOrganizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agStaffResourceOrganizationTable extends PluginagStaffResourceOrganizationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agStaffResourceOrganizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agStaffResourceOrganization');
    }
}