<?php

/**
 * agGeoRelationshipTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agGeoRelationshipTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agGeoRelationshipTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agGeoRelationshipType');
    }
}