<?php

/**
 * agEventAuditSqlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventAuditSqlTable extends PluginagEventAuditSqlTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventAuditSqlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventAuditSql');
    }
}