<?php

/**
 * agEventStaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventStaffTable extends PluginagEventStaffTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventStaffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventStaff');
    }
}