<?php

/**
 * agEventAffectedAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventAffectedAreaTable extends PluginagEventAffectedAreaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventAffectedAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventAffectedArea');
    }
}