<?php

/**
 * agEventStaffRotationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventStaffRotationTable extends PluginagEventStaffRotationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventStaffRotationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventStaffRotation');
    }
}