<?php

/**
 * agEventFacilityGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agEventFacilityGroupTable extends PluginagEventFacilityGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agEventFacilityGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agEventFacilityGroup');
    }
}