<?php

/**
 * agStaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agStaffTable extends PluginagStaffTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object agStaffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agStaff');
    }
}