<?php

/**
 * agStaffAllocationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginagStaffAllocationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agStaffAllocationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agStaffAllocationStatus');
    }
}
