<?php

/**
 * PluginagStaffAllocationStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginagStaffAllocationStatus extends BaseagStaffAllocationStatus
{
  /**
   * Method to return the event staff post-deployed status
   */
  public static function getEventStaffDeployedStatusId()
  {
    return agDoctrineQuery::create()
      ->select('sas.id')
        ->from('agStaffAllocationStatus sas')
        ->where('sas.staff_allocation_status = ?', 'Committed')
        ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
  }
}