<?php

/**
 * BaseagGeoCoordinate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $longitude
 * @property decimal $latitude
 * @property Doctrine_Collection $agGeoFeature
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method decimal             getLongitude()    Returns the current record's "longitude" value
 * @method decimal             getLatitude()     Returns the current record's "latitude" value
 * @method Doctrine_Collection getAgGeoFeature() Returns the current record's "agGeoFeature" collection
 * @method agGeoCoordinate     setId()           Sets the current record's "id" value
 * @method agGeoCoordinate     setLongitude()    Sets the current record's "longitude" value
 * @method agGeoCoordinate     setLatitude()     Sets the current record's "latitude" value
 * @method agGeoCoordinate     setAgGeoFeature() Sets the current record's "agGeoFeature" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagGeoCoordinate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_geo_coordinate');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('longitude', 'decimal', 12, array(
             'scale' => 8,
             'type' => 'decimal',
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('latitude', 'decimal', 12, array(
             'scale' => 8,
             'type' => 'decimal',
             'notnull' => true,
             'length' => 12,
             ));


        $this->index('idx_geo_coordinate_latitude', array(
             'fields' => 
             array(
              0 => 'latitude',
             ),
             ));
        $this->index('idx_geo_coordinate_longitude', array(
             'fields' => 
             array(
              0 => 'longitude',
             ),
             ));
        $this->index('uc_geo_coordinate_lat_long', array(
             'fields' => 
             array(
              0 => 'latitude',
              1 => 'longitude',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agGeoFeature', array(
             'local' => 'id',
             'foreign' => 'geo_coordinate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}