<?php

/**
 * PlugintempGeoRelationshipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintempGeoRelationshipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintempGeoRelationshipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintempGeoRelationship');
    }
}