<?php

/**
 * BaseagEventAffectedArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $affected_area_id
 * @property agEvent $agEvent
 * @property agAffectedArea $agAffectedArea
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getEventId()          Returns the current record's "event_id" value
 * @method integer             getAffectedAreaId()   Returns the current record's "affected_area_id" value
 * @method agEvent             getAgEvent()          Returns the current record's "agEvent" value
 * @method agAffectedArea      getAgAffectedArea()   Returns the current record's "agAffectedArea" value
 * @method agEventAffectedArea setId()               Sets the current record's "id" value
 * @method agEventAffectedArea setEventId()          Sets the current record's "event_id" value
 * @method agEventAffectedArea setAffectedAreaId()   Sets the current record's "affected_area_id" value
 * @method agEventAffectedArea setAgEvent()          Sets the current record's "agEvent" value
 * @method agEventAffectedArea setAgAffectedArea()   Sets the current record's "agAffectedArea" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagEventAffectedArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_event_affected_area');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('affected_area_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('UX_agEventAffectedArea', array(
             'fields' => 
             array(
              0 => 'event_id',
              1 => 'affected_area_id',
             ),
             'type' => 'unique',
             ));
        $this->index('agEventAffectedArea_eventId', array(
             'fields' => 
             array(
              0 => 'event_id',
             ),
             ));
        $this->index('agEventAffectedArea_affectedAreaId', array(
             'fields' => 
             array(
              0 => 'affected_area_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agEvent', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('agAffectedArea', array(
             'local' => 'affected_area_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}