<?php

/**
 * BaseagEventStaffSignIn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_staff_shift_id
 * @property timestamp $signin
 * @property timestamp $signout
 * @property agEventStaffShift $agEventStaffShift
 * 
 * @method integer            getId()                   Returns the current record's "id" value
 * @method integer            getEventStaffShiftId()    Returns the current record's "event_staff_shift_id" value
 * @method timestamp          getSignin()               Returns the current record's "signin" value
 * @method timestamp          getSignout()              Returns the current record's "signout" value
 * @method agEventStaffShift  getAgEventStaffShift()    Returns the current record's "agEventStaffShift" value
 * @method agEventStaffSignIn setId()                   Sets the current record's "id" value
 * @method agEventStaffSignIn setEventStaffShiftId()    Sets the current record's "event_staff_shift_id" value
 * @method agEventStaffSignIn setSignin()               Sets the current record's "signin" value
 * @method agEventStaffSignIn setSignout()              Sets the current record's "signout" value
 * @method agEventStaffSignIn setAgEventStaffShift()    Sets the current record's "agEventStaffShift" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagEventStaffSignIn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_event_staff_sign_in');
        $this->hasColumn('id', 'integer', 5, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('event_staff_shift_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('signin', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('signout', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('UX_agEventStaffSignIn', array(
             'fields' => 
             array(
              0 => 'event_staff_shift_id',
              1 => 'signin',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agEventStaffShift', array(
             'local' => 'event_staff_shift_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}