<?php

/**
 * BaseagEventServiceArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Doctrine_Collection $agEventServiceAreaComposite
 * @property Doctrine_Collection $agEventFacilityDistribution
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method Doctrine_Collection getAgEventServiceAreaComposite() Returns the current record's "agEventServiceAreaComposite" collection
 * @method Doctrine_Collection getAgEventFacilityDistribution() Returns the current record's "agEventFacilityDistribution" collection
 * @method agEventServiceArea  setId()                          Sets the current record's "id" value
 * @method agEventServiceArea  setAgEventServiceAreaComposite() Sets the current record's "agEventServiceAreaComposite" collection
 * @method agEventServiceArea  setAgEventFacilityDistribution() Sets the current record's "agEventFacilityDistribution" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagEventServiceArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_event_service_area');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agEventServiceAreaComposite', array(
             'local' => 'id',
             'foreign' => 'event_service_area_id'));

        $this->hasMany('agEventFacilityDistribution', array(
             'local' => 'id',
             'foreign' => 'event_service_area_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}