<?php

/**
 * BaseagEventFacilityResourceStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_facility_resource_id
 * @property timestamp $time_stamp
 * @property integer $facility_resource_allocation_status_id
 * @property agEventFacilityResource $agEventFacilityResource
 * @property agFacilityResourceAllocationStatus $agFacilityResourceAllocationStatus
 * 
 * @method integer                            getId()                                     Returns the current record's "id" value
 * @method integer                            getEventFacilityResourceId()                Returns the current record's "event_facility_resource_id" value
 * @method timestamp                          getTimeStamp()                              Returns the current record's "time_stamp" value
 * @method integer                            getFacilityResourceAllocationStatusId()     Returns the current record's "facility_resource_allocation_status_id" value
 * @method agEventFacilityResource            getAgEventFacilityResource()                Returns the current record's "agEventFacilityResource" value
 * @method agFacilityResourceAllocationStatus getAgFacilityResourceAllocationStatus()     Returns the current record's "agFacilityResourceAllocationStatus" value
 * @method agEventFacilityResourceStatus      setId()                                     Sets the current record's "id" value
 * @method agEventFacilityResourceStatus      setEventFacilityResourceId()                Sets the current record's "event_facility_resource_id" value
 * @method agEventFacilityResourceStatus      setTimeStamp()                              Sets the current record's "time_stamp" value
 * @method agEventFacilityResourceStatus      setFacilityResourceAllocationStatusId()     Sets the current record's "facility_resource_allocation_status_id" value
 * @method agEventFacilityResourceStatus      setAgEventFacilityResource()                Sets the current record's "agEventFacilityResource" value
 * @method agEventFacilityResourceStatus      setAgFacilityResourceAllocationStatus()     Sets the current record's "agFacilityResourceAllocationStatus" value
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagEventFacilityResourceStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_event_facility_resource_status');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('event_facility_resource_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('time_stamp', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('facility_resource_allocation_status_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));


        $this->index('UX_agEventFacilityResourceStatus', array(
             'fields' => 
             array(
              0 => 'event_facility_resource_id',
              1 => 'time_stamp',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('agEventFacilityResource', array(
             'local' => 'event_facility_resource_id',
             'foreign' => 'id'));

        $this->hasOne('agFacilityResourceAllocationStatus', array(
             'local' => 'facility_resource_allocation_status_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}