<?php

/**
 * agGeoMatchScoreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class agGeoMatchScoreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object agGeoMatchScoreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('agGeoMatchScore');
    }
}