<?php

/**
 * BaseagGeoSourceScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $geo_source_score
 * @property integer $geo_source_score_value
 * @property Doctrine_Collection $agGeoSource
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getGeoSourceScore()         Returns the current record's "geo_source_score" value
 * @method integer             getGeoSourceScoreValue()    Returns the current record's "geo_source_score_value" value
 * @method Doctrine_Collection getAgGeoSource()            Returns the current record's "agGeoSource" collection
 * @method agGeoSourceScore    setId()                     Sets the current record's "id" value
 * @method agGeoSourceScore    setGeoSourceScore()         Sets the current record's "geo_source_score" value
 * @method agGeoSourceScore    setGeoSourceScoreValue()    Sets the current record's "geo_source_score_value" value
 * @method agGeoSourceScore    setAgGeoSource()            Sets the current record's "agGeoSource" collection
 * 
 * @package    AGASTI_CORE
 * @subpackage model
 * @author     CUNY SPS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseagGeoSourceScore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ag_geo_source_score');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('geo_source_score', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('geo_source_score_value', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));


        $this->index('UX_agGeoSourceScore', array(
             'fields' => 
             array(
              0 => 'geo_source_score',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('agGeoSource', array(
             'local' => 'id',
             'foreign' => 'geo_source_score_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}