<?php

/**
 * Agasti Person Form Class - A class to generate either a 'new person' or
 * 'edit person' form
 *
 * PHP Version 5.3
 *
 * LICENSE: This source file is subject to LGPLv2.1 license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * @author Charles Wisniewski, CUNY SPS
 * @author Nils Stolpe, CUNY SPS
 * @author Ilya Gulko, CUNY SPS
 *
 * @todo Major clean-up required.
 *
 * Copyright of the Sahana Software Foundation, sahanafoundation.org
 * */
class agPersonForm extends BaseagPersonForm
{
  /**
  * Configures the form, setting up widgets and some meta-data.
  **/
  public function configure()
  {
    sfProjectConfiguration::getActive()->loadHelpers(array ('Helper','Url', 'Asset', 'Tag'));
    $this->wikiUrl = url_for('@wiki');
    $this->configureWidgets();
    $this->agEntity = $this->getObject()->getAgEntity();
    $this->embedAgPersonForms();
  }

  public function configureWidgets()
  {
    unset($this['created_at'],
        $this['updated_at'],
        $this['ag_language_list'],
        $this['ag_country_list'],
        $this['ag_aid_provider_list'],
        $this['ag_import_list'],
        $this['ag_residential_status_list'],
        $this['ag_import_type_list'],
        $this['ag_account_list'],
        $this['ag_phone_contact_type_list'],
        $this['ag_email_contact_type_list'],
        $this['ag_address_contact_type_list'],
        $this['ag_phone_contact_list'],
        $this['ag_email_contact_list'],
        $this['ag_email_contact'],
        $this['ag_person_name_list'],
        $this['ag_person_name_type_list'],
        $this['entity_id'],
        $this['ag_person_custom_field_list']);

    /**
     * Remove multiple selection from widgets that have been autogenerated with multiple selection
     * but don't actually need it.
     * */
    $this->setWidget(
        'ag_sex_list', new sfWidgetFormDoctrineChoice(
            array('multiple' => FALSE, 'model' => 'agSex')
        )
    );
    $this->setWidget(
        'ag_ethnicity_list', new sfWidgetFormDoctrineChoice(
            array('multiple' => FALSE, 'model' => 'agEthnicity')
        )
    );
    $this->setWidget(
        'ag_marital_status_list', new sfWidgetFormDoctrineChoice(
            array('multiple' => FALSE, 'model' => 'agMaritalStatus')
        )
    );

    /**
     * Give the list widgets more aesthetically appealing and descriptive labels.
     * */
    $this->widgetSchema->setLabel('ag_sex_list', 'Sex');
    $this->widgetSchema->setLabel('ag_religion_list', 'Religion');
    $this->widgetSchema->setLabel('ag_profession_list', 'Profession');
    $this->widgetSchema->setLabel('ag_nationality_list', 'Nationality');
    $this->widgetSchema->setLabel('ag_ethnicity_list', 'Ethnicity');
    $this->widgetSchema->setLabel('ag_marital_status_list', 'Marital Status');

    /**
     * Narrow down the options for select lists by using app_display. Lots of repetetive code,
     * could be moved to function.
     * */
    $this->widgetSchema['ag_nationality_list']->addOption(
        'query', agDoctrineQuery::create()->select('a.nationality')->from('agNationality a')->where('a.app_display = 1')
    );

    $this->widgetSchema['ag_religion_list']->addOption(
        'query', agDoctrineQuery::create()->select('a.religion')->from('agReligion a')->where('a.app_display = 1')
    );

    $this->widgetSchema['ag_profession_list']->addOption(
        'query',
        agDoctrineQuery::create()->select('a.profession')->from('agProfession a')->where('a.app_display = 1')
    );

    $this->widgetSchema['ag_ethnicity_list']->addOption(
        'query',
        agDoctrineQuery::create()->select('a.ethnicity')->from('agEthnicity a')->where('a.app_display = 1')
    );

    $this->widgetSchema['ag_sex_list']->addOption(
        'query',
        agDoctrineQuery::create()->select('a.sex')->from('agSex a')->where('a.app_display = 1')
    );

    $this->widgetSchema['ag_marital_status_list']->addOption(
        'query',
        agDoctrineQuery::create()->select('a.marital_status')->from('agMaritalStatus a')->where('a.app_display = 1')
    );
  }

  /**
   * This function sets up the embedded forms by
   * calling all of the embed[Foo]Forms methods.
   * */
  public function embedAgPersonForms()
  {
    $this->embedDateOfBirthForm();
    $this->embedContactForms();
    $this->embedAddressForm();
    $this->embedPrimaryForms();
  }

  public function embedPrimaryForms()
  {
    $primaryContainer = new sfForm();
    $primaryContainerFormatter = new agFormatterPrimaryLevelOne($primaryContainer->getWidgetSchema());
    $primaryContainer->getWidgetSchema()->addFormFormatter('primaryContainerFormatter', $primaryContainerFormatter);
    $primaryContainer->getWidgetSchema()->setFormFormatterName('primaryContainerFormatter');
    $this->embedNameForm($primaryContainer);
    $this->embedLanguageForm($primaryContainer);
    $this->embedForm('Primary', $primaryContainer);
  }
  
  public function embedContactForms()
  {
    $contactContainer = new sfForm();
    $contactContainerFormatter = new agFormatterAddressLevelOne($contactContainer->getWidgetSchema());
    $contactContainer->getWidgetSchema()->addFormFormatter('contactContainerFormatter', $contactContainerFormatter);
    $contactContainer->getWidgetSchema()->setFormFormatterName('contactContainerFormatter');
    $this->embedEmailForm($contactContainer);
    $this->embedPhoneForm($contactContainer);
    $this->embedForm('Contact', $contactContainer);
  }
  /**
   * This function sets up the date of birth form.
   *
   * @todo refactor this function similarly to embedNameForm() and embedEmailForm().
   * Get rid of default use.
   * */
  public function embedDateOfBirthForm()
  {
    $dateOfBirthForm = new agEmbeddedPersonDateOfBirthForm($this->getObject()->getAgPersonDateOfBirth());
    $dateOfBirthForm->getWidgetSchema()->setLabel('date_of_birth', 'Date of Birth <a href="' . $this->wikiUrl .  '/doku.php?id=tooltip:date_of_birth&do=export_xhtmlbody" class="tooltipTrigger" title="Date of Birth">?</a>');
    $dateOfBirthForm->setDefault('person_id', $this->getObject()->id);
    $this->embedForm('Date of Birth', $dateOfBirthForm);
  }

  /**
   * This function sets up language forms using agEmbeddedAgPersonMjAgLanguageForm
   * and agEmbeddedAgPersonLanguageCompetencyForm.
   *
   * @todo refactor this function similarly to embedNameForm() and embedEmailForm().
   * */
  public function embedLanguageForm($primaryContainer)
  {
    $this->ag_person_language_formats = Doctrine::getTable('agLanguageFormat')->createQuery('a')->execute();
    //create the container form and set it's formatter.
    $languageContainer = new sfForm();
    $langConDeco = new agWidgetFormSchemaFormatterSubContainer($languageContainer->getWidgetSchema());
    $languageContainer->getWidgetSchema()->addFormFormatter('langConDeco', $langConDeco);
    $languageContainer->getWidgetSchema()->setFormFormatterName('langConDeco');

    //set the max limit for the iterator for the $langSubContainer forms to 2.
    //Then check the languages, if they're greater than 1, reset it to that greater number.
    $m = 2;
//    if (count($this->getObject()->getAgPersonMjAgLanguage()) > 1) {
//      $m = count($this->getObject()->getAgPersonMjAgLanguage()) + 1;
//    }

    //Create the $languageSubContainer forms and set their formatters.
    for ($i = 1; $i <= $m; $i++) {
      $languageSubContainer = new sfForm(); //subcontainer form to hold language and join forms.
      $langSubConDeco = new agWidgetFormSchemaFormatterSubContainer($languageSubContainer->getWidgetSchema());
      $languageSubContainer->getWidgetSchema()->addFormFormatter('langSubConDeco', $langSubConDeco);
      $languageSubContainer->getWidgetSchema()->setFormFormatterName('langSubConDeco');

      $personLanguages = $this->getObject()->getAgPersonMjAgLanguage();
      // If the current person already has some languages,
      // set the default id and language values of the form.
      $languageForm = new agEmbeddedAgPersonMjAgLanguageForm();
      $languageForm->setDefault('priority', $i);
      if (isset($personLanguages[$i - 1])) {
        //$languageForm = new agEmbeddedAgPersonMjAgLanguageForm($personLanguages[$i - 1]);
        $languageForm->setDefaults(
            array(
              'language_id' => $personLanguages[$i - 1]->language_id,
              'id' => $personLanguages[$i - 1]->id,
              //Right now, priority is set to the order forms show up in.
              // Somewhat sensible, maybe indicate this on frontend?
              'priority' => $i
            )
        );
      }
      // If not, just create the empty forms.
      // Only create the labels if this is the first language, so everything shows up in a matrix.
//      if ($i <> 1) {
//        $languageForm->widgetSchema->setLabel('language_id', FALSE);
//      } else {
        $languageForm->widgetSchema->setLabel('language_id', 'Language Name');
//      }

      $languageSubContainer->embedForm('language', $languageForm);
      $languageSubContainer->widgetSchema->setLabel('language', FALSE);

      // Create the forms for language competency, one for each format.
      // If the person has them already, stick in the objects.
      foreach ($this->ag_person_language_formats as $langFormat) {
        $formatForm = new agEmbeddedAgPersonLanguageCompetencyForm();
        $formatForm->setDefault('language_format_id', $langFormat->id);
        // If the $languageForm has a default for language, check for related competencies.
        if ($languageForm->getDefault('language_id') <> NULL) {
          $q = agDoctrineQuery::create()
                  ->select('a.id')
                  ->from('agPersonMjAgLanguage a')
                  ->where('a.person_id = ?', $this->getObject()->id)
                  ->andWhere('a.language_id =?', $languageForm->getDefault('id'));

          $competencyQuery = Doctrine_query::create()
                  ->select('a.*')
                  ->from('agPersonLanguageCompetency a')
                  ->where('person_language_id = ?', $languageForm->getDefault('id'))
                  ->andWhere('language_format_id = ?', $langFormat->id);
          // Check if a competency has been assigned to the current language/language-format combo.
          // If it has, fill the form w/ the object. If not, make an empty form.
          if ($competencyObject = $competencyQuery->fetchOne()) {
            $formatForm = new agEmbeddedAgPersonLanguageCompetencyForm($competencyObject);
          }
        } else {
          $formatForm->setDefault('language_format_id', $langFormat->id);
        }
        // If the $languagForm doesn't have an object, make an empty $formatForm.
        // Same as with $languageForm. We only want labels for the first row of objects.
        // The others will fall directly under, so the labels should be understandable.
//        if ($i <> 1) {
//          $formatForm->widgetSchema->setLabel('language_competency_id', FALSE);
//        } else {
          $formatForm->widgetSchema->setLabel(
              'language_competency_id',
              ucwords($langFormat->language_format)
          );
//        }
        $languageSubContainer->embedForm($langFormat->language_format, $formatForm);
        $languageSubContainer->widgetSchema->setLabel($langFormat->language_format, FALSE);
      }
      $languageContainer->embedForm('language ' . $i, $languageSubContainer);
      $languageContainer->widgetSchema->setLabel('language ' . $i, FALSE);
    }
    $primaryContainer->embedForm('Languages', $languageContainer);
    $primaryContainer->widgetSchema['Languages']->setLabel('Languages <a href="' . $this->wikiUrl . '/doku.php?id=tooltip:languages&do=export_xhtmlbody" class="tooltipTrigger" title="Languages">?</a>');
  }

  /**
   * This function sets up the embedded agEmbeddedAgPersonNameForms, one for each agPersonNameType,
   * populated with the agPersonName that corresponds to the current agPerson and
   * agPersonNameType (if it exists).
   * */
  public function embedNameForm($primaryContainer)
  {
    $nameHelper = new agPersonNameHelper();
    $defaultNameComponents = $nameHelper->defaultNameComponents;
    unset($nameHelper);
    
    foreach($defaultNameComponents as $dnc) {
      $nameTypeIds[] = $dnc[0];
    }
    // Get the name types we need, as determined by the defaults.
    $nameTypesPreSort = agDoctrineQuery::create()
                   ->select('id')
                   ->addSelect('person_name_type')
                   ->from('agPersonNameType')
                   ->whereIn('id', $nameTypeIds)
                   ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);

    foreach($defaultNameComponents as $key => $defaultNameComponent) {
      foreach($nameTypesPreSort as $nameTypePreSort) {
        if($nameTypePreSort['id'] == $defaultNameComponent[0]) {
          $nameTypes[$key]['person_name_type'] = $nameTypePreSort['person_name_type'];
          $nameTypes[$key]['id'] = $nameTypePreSort['id'];
        }
      }
    }
    $nameContainer = new sfForm();
    $nameConDeco = new agWidgetFormSchemaFormatterSubContainer($nameContainer->getWidgetSchema());
    $nameContainer->getWidgetSchema()->addFormFormatter('nameConDeco', $nameConDeco);
    $nameContainer->getWidgetSchema()->setFormFormatterName('nameConDeco');
    foreach ($nameTypes as $nameType) {
      if ($id = $this->getObject()->id) {
        $nameObject = agDoctrineQuery::create()
                ->from('agPersonName pn')
                ->where('pn.id IN (SELECT jn.person_name_id FROM agPersonMjAgPersonName jn WHERE jn.person_id = ? AND person_name_type_id = ?)', array($id, $nameType['id']))
                ->execute()->getFirst();
      }
      $nameForm = new agEmbeddedAgPersonNameForm(isset($nameObject) ? $nameObject : NULL);
      $nameForm->widgetSchema->setLabel('person_name', ucwords($nameType['person_name_type']));
      $nameContainer->embedForm($nameType['person_name_type'], $nameForm);
    }
    $primaryContainer->embedForm('Name', $nameContainer);
    $primaryContainer->widgetSchema['Name']->setLabel('Name <a href="' . $this->wikiUrl . '/doku.php?id=tooltip:name&do=export_xhtmlbody" class="tooltipTrigger" title="Name">?</a>');
  }

  /**
   * This block sets up the embedded agEmbeddedAgEmailContactForms, one for each
   * agEmailContactType, populated with the agPersonName that corresponds to the current
   * agPerson and agEmailContactType (if it exists).
   *
   * @todo     make a new formatter for these forms to use and set it up, so we
   *           don't need to set label to FALSE.
   * */
  public function embedEmailForm($contactContainer)
  {
    $this->ag_email_contact_types = Doctrine::getTable('agEmailContactType')->createQuery('a')->execute();

    $emailContainer = new sfForm();
    $emailContainerFormatter = new agFormatterAddressLevelTwo($emailContainer->getWidgetSchema());
    $emailContainer->getWidgetSchema()->addFormFormatter('emailContainerFormatter', $emailContainerFormatter);
    $emailContainer->getWidgetSchema()->setFormFormatterName('emailContainerFormatter');
    foreach ($this->ag_email_contact_types as $emailContactType) {
      if ($id = $this->getObject()->entity_id) {
        $emailObject = Doctrine_query::create()
                ->from('agEmailContact ec')
                ->where('ec.id IN (SELECT jn.email_contact_id FROM agEntityEmailContact jn WHERE jn.entity_id = ? AND email_contact_type_id = ?)', array($id, $emailContactType->id))
                ->execute()->getFirst();
      }
      $emailContactForm = new agEmbeddedAgEmailContactForm(isset($emailObject) ? $emailObject : NULL);
      $emailContactFormatter = new agFormatterAddressLevelThree($emailContactForm->getWidgetSchema());
      $emailContactForm->getWidgetSchema()->addFormFormatter('emailContactFormatter', $emailContactFormatter);
      $emailContactForm->getWidgetSchema()->setFormFormatterName('emailContactFormatter');
      $emailContactForm->widgetSchema->setLabel('email_contact', FALSE);
      
      $emailContainer->embedForm($emailContactType->getEmailContactType(), $emailContactForm);
    }
    $contactContainer->embedForm('Email', $emailContainer);
    $contactContainer->widgetSchema['Email']->setLabel('Email <a href="' . $this->wikiUrl . '/doku.php?id=tooltip:contact_email&do=export_xhtmlbody" class="tooltipTrigger" title="Email">?</a>');
  }

  /**
   * This function sets up the embedded agEmbeddedAgPhoneContactForms, one for each
   * agPhoneContactType, populated with the agPersonName that corresponds to the
   * current agPerson and agPhoneContactType (if it exists).
   *
   * @todo refactor this function similarly to embedNameForm() and embedEmailForm().
   * */
  public function embedPhoneForm($contactContainer)
  {
    $this->ag_phone_contact_types = Doctrine::getTable('agPhoneContactType')->createQuery('a')->execute();

    $phoneContainer = new sfForm(array(), array());
    $phoneContainerFormatter = new agFormatterAddressLevelTwo($phoneContainer->getWidgetSchema());
    $phoneContainer->getWidgetSchema()->addFormFormatter('phoneContainerFormatter', $phoneContainerFormatter);
    $phoneContainer->getWidgetSchema()->setFormFormatterName('phoneContainerFormatter');
    foreach ($this->ag_phone_contact_types as $phoneContactType) {
      if ($id = $this->getObject()->entity_id) {
        $phoneObject = Doctrine_query::create()
                ->from('agPhoneContact pc')
                ->where('pc.id IN (SELECT jn.phone_contact_id FROM agEntityPhoneContact jn WHERE jn.entity_id = ? AND phone_contact_type_id = ?)', array($id, $phoneContactType->id))
                ->execute()->getFirst();
      }
      $phoneContactForm = new agEmbeddedAgPhoneContactForm(isset($phoneObject) ? $phoneObject : NULL);
      $phoneContactFormatter = new agFormatterAddressLevelThree($phoneContactForm->getWidgetSchema());
      $phoneContactForm->getWidgetSchema()->addFormFormatter('phoneContactFormatter', $phoneContactFormatter);
      $phoneContactForm->getWidgetSchema()->setFormFormatterName('phoneContactFormatter');
      $phoneContactForm->widgetSchema->setLabel('phone_contact', FALSE);

      $phoneContainer->embedForm($phoneContactType->getPhoneContactType(), $phoneContactForm);
    }

    $contactContainer->embedForm('Phone', $phoneContainer);
    $contactContainer->widgetSchema['Phone']->setLabel('Phone <a href="' . $this->wikiUrl . '/doku.php?id=tooltip:contact_phone&do=export_xhtmlbody" class="tooltipTrigger" title="Phone">?</a>');
  }

  /**
   * This function sets up address forms.
   *
   * @todo refactor this function similarly to embedNameForm() and embedEmailForm().
   * */
  public function embedAddressForm()
  {
    $this->address_contact_types = Doctrine::getTable('agAddressContactType')->createQuery('a')->execute();
    $this->address_formats = Doctrine::getTable('agAddressFormat')
            ->createQuery('addressFormat')
            ->select('af.*, ae.*')
            ->from('agAddressFormat af, af.agAddressElement ae')
            ->execute();

    $addressIds = agDoctrineQuery::create()
                ->select('address_id')
                ->from('agEntityAddressContact')
                ->where('entity_id = ?', $this->getObject()->getEntityId())
                ->execute(array(), 'single_value_array');

    // This loop makes a 3d array of line sequence values (as the first level key),
    // inline sequence values (as the second level key), address element values
    // (as the third level string key), and address element ids (as the third level value).

    /**
     * @todo this works fine for now, since we only have one address format, but should be
     * refactored to create a new array from values in the agAddressFormat table for each
     * address_standard_id in that table.
     * */
//    foreach ($this->address_formats as $af) {
//      $addressElements[$af->line_sequence][$af->inline_sequence][$af->getAgAddressElement()->address_element] = $af->getAgAddressElement()->id;
//    }

    $elementIds = agDoctrineQuery::create()
            ->select('ae.id')
            ->from('agAddressElement ae')
            ->whereIn('address_element', array('country', 'state'))
            ->orderby('address_element')
            ->execute(array(), Doctrine_Core::HYDRATE_NONE);
    $countryAddressElementId = $elementIds[0][0];
    $stateAddressElementId = $elementIds[1][0];

    $countryList = Doctrine::getTable('agCountry')
            ->createQuery('addressCountries')
            ->select('c.country')
            ->from('agCountry c');

    // This loop makes a 3d array of line sequence values (as the first level key),
    // inline sequence values (as the second level key), address element values
    // (as the third level string key), and address element ids (as the third level value).
    foreach ($this->address_formats as $af) {
      $addressElements[$af->line_sequence][$af->inline_sequence][$af->getAgAddressElement()->address_element]['id'] = $af->getAgAddressElement()->id;
      $addressElements[$af->line_sequence][$af->inline_sequence][$af->getAgAddressElement()->address_element]['fieldType'] = $af->getAgFieldType()->getFieldType();
    }
    $addressContainer = new sfForm(array(), array());
//    $addressContainer->widgetSchema->setFormFormatterName('list');
    $addressContainerFormatter = new agFormatterAddressLevelOne($addressContainer->getWidgetSchema());
    $addressContainer->getWidgetSchema()->addFormFormatter('addConDeco', $addressContainerFormatter);
    $addressContainer->getWidgetSchema()->setFormFormatterName('addConDeco');

    $stateList = Doctrine::getTable('agAddressValue')
            ->createQuery('addressStates')
            ->select('a.value')
            ->from('agAddressValue a')
            ->where('a.address_element_id = 4');

    $this->entityAddress = Doctrine::getTable('agEntity')
            ->createQuery('entityAddresses')
            ->select('e.*, eac.*, act.*, a.*, as.*, aav.*, av.*, p.*, ae.*')
            ->from(
                'agEntity e, e.agEntityAddressContact eac, eac.agAddressContactType act,
              eac.agAddress a, a.agAddressStandard as, a.agAddressMjAgAddressValue aav,
              aav.agAddressValue av, av.agAddressElement ae, e.agPerson p'
            )
            ->where('e.id = ?', $this->agEntity->getId())
            ->fetchOne();


    foreach ($this->address_contact_types as $address_contact_type) {
      $addressSubContainer = new sfForm(array(), array());
      $addressSubContainerFormatter = new agFormatterAddressLevelTwo($addressSubContainer->getWidgetSchema());
      $addressSubContainer->getWidgetSchema()->addFormFormatter('subFormatter', $addressSubContainerFormatter);
      $addressSubContainer->getWidgetSchema()->setFormFormatterName('subFormatter');
      // Sublevel container forms beneath address to hold a complete address for each address type.
      foreach ($addressElements as $ae) {
        foreach ($ae as $addressElement) {
          $valueForm = new agEmbeddedAgAddressValueForm();
          $valueFormFormatter = new agFormatterAddressLevelThree($valueForm->getWidgetSchema());
          $valueForm->getWidgetSchema()->addFormFormatter('valFormatter', $valueFormFormatter);
          $valueForm->getWidgetSchema()->setFormFormatterName('valFormatter');
//          $valueForm->widgetSchema->setFormFormatterName('list');
          // Lowest level address form, actually holds the data.
          $valueForm->setDefault('address_element_id', $addressElement[key($addressElement)]['id']);
          //set the default address_element_id.
          $valueForm->widgetSchema->setLabel('value', FALSE);
          //hide the 'value' field label.
          // This sets the widget for the agEmbeddedAddressValueForm. Generally, it will be a text
          // widget, but in the case of things like state, a select box is preferred.
          if ($addressElement[key($addressElement)]['fieldType'] == 'sfWidgetFormDoctrineChoice') {
            if ($addressElement[key($addressElement)]['id'] == $stateAddressElementId) {
              $valueForm->setWidget(
                  'value',
                  new sfWidgetFormDoctrineChoice(
                      array(
                        'multiple' => FALSE,
                        'model' => 'agAddressValue',
                        'add_empty' => TRUE,
                        'key_method' => 'getValue'
                      ),
                      array('class' => 'inputGray')
                  )
              );

              $valueForm->widgetSchema->setLabel('value', FALSE);

              $valueForm->widgetSchema['value']->addOption(
                  'query',
                  $stateList
              );
            } elseif ($addressElement[key($addressElement)]['id'] == $countryAddressElementId) {
              $valueForm->setWidget(
                  'value',
                  new sfWidgetFormDoctrineChoice(
                      array(
                        'multiple' => FALSE,
                        'model' => 'agAddressValue',
                        'add_empty' => TRUE,
                        'key_method' => 'getCountry'
                      ),
                      array('class' => 'inputGray')
                  )
              );

              $valueForm->widgetSchema->setLabel('value', FALSE);

              $valueForm->widgetSchema['value']->addOption(
                  'query',
                  $countryList
              );
            }
          }

          if (isset($this->entityAddress) && $this->entityAddress) {
            // Each of the agPerson's existing address records.
            foreach ($this->entityAddress->getAgEntityAddressContact() as $current) {
              if ($current->address_contact_type_id == $address_contact_type->id) {
                // Make a new agAddressHelper() and get geo-coordinates with it.
                // put those coordinates into the $geoForm and lose the helper.
                $addressHelper = new agAddressHelper();
                // make a new form for the lat and long.
                $geoForm = new agEmbeddedGeoAddressForm();
                // See if the address has any geo data. If it does, put that data in the form.
                if($addressCoords = $addressHelper->getAddressCoordinates(array($current['address_id']))) {
                  $geoForm->setDefault('latitude', $addressCoords[$current['address_id']]['latitude']);
                  $geoForm->setDefault('longitude', $addressCoords[$current['address_id']]['longitude']);
                }
                unset($addressHelper);
                
                //Get the joins from agAddress to agAddressValue
                foreach ($current->getAgAddress()->getAgAddressMjAgAddressValue() as $av) {
                  if ($av->getAgAddressValue()->getAgAddressElement()->address_element == key($addressElement)) {
                    $valueForm->setDefault('value', $av->getAgAddressValue()->value);
                    $valueForm->id_holder = $av->getAgAddressValue()->id;
                  }
                }
              }
            }
          }
          //set an addressType property for the form so the type can be used when saving.
          $valueForm->addressType = $address_contact_type->address_contact_type;
          //Embed the address elements.
          $addressSubContainer->embedForm(key($addressElement), $valueForm);
        }
      }
      // Get rid of a set $geoForm for the next pass.
      if (!isset($geoForm)) {
        $geoForm = new agEmbeddedGeoAddressForm();
      }
      $addressSubContainer->embedForm('Geo Data', $geoForm);
      unset($geoForm);
      $addressSubContainer->getWidgetSchema()->setLabel('Geo Data', FALSE);
      //Embed the addresses-by-type
      $addressContainer->embedForm($address_contact_type, $addressSubContainer);
    }
    //Embed all the addresses into agPersonForm.
    $this->embedForm('Address', $addressContainer);
  }

  /**
   * Saves data in the embedded date of birth form.
   *
   * @param agEmbeddedPersonDateOfBirthForm $form
   *
   * @todo: The '0000-00-00' below is pretty hackish and should be fixed. It
   * prevents a DB error for a field that should not be NULL formValuesAreBlank()
   * or something similar should really be used, in updateObject, to catch this
   * earlier and unset.
   * */
  public function saveDateOfBirthForm($form)
  {
    if ($form->getObject()->person_id == NULL && $form->getObject()->date_of_birth <> '0000-00-00') {
      $form->getObject()->person_id = $this->getObject()->id;
      $form->getObject()->save();
    } elseif ($form->getObject()->date_of_birth == '0000-00-00' && $form->getObject()->person_id <> NULL) {
      $form->getObject()->delete();
    } elseif ($form->getObject()->date_of_birth <> '0000-00-00' && $form->getObject()->person_id <> NULL) {
      $form->getObject()->save();
    }
  }

  /**
   * Saves data in an embedded name form.
   *
   * @param string $key
   * the key of the agEmbeddedAgPersonNameForm being acted on. It should correspond to the name_type
   * value that is linked to the name and person in the agPersonMjAgPersonName table.
   *
   * @param agEmbeddedAgPersonNameForm()
   * the name form being saved
   *
   * @param array $values
   * incoming values from the form, retrieved in saveEmbeddedForms()
   * */
  public function saveNameForm($key, $form, $values)
  {
    $form->updateObject($values);
    // Find the agPersonNameType()->id for the current form using its $key
    // (which corresponds to an agPersonNameType).
    $typeId = agDoctrineQuery::create()
            ->select('a.id')
            ->from('agPersonNameType a')
            ->where('a.person_name_type = ?', $key)
            ->execute(NULL, Doctrine_Core::HYDRATE_SINGLE_SCALAR);

    // Check to see if the name object is unmodified and that a value other than
    // NULL was submitted.
    if ($form->getObject()->isModified() && $form->getObject()->person_name <> NULL) {
      // See if the submitted name already exists in the db.
      $nameObject = Doctrine::getTable('agPersonName')
              ->findByDql('person_name = ?', $form->getObject()->person_name)
              ->getFirst();

      // If it doesn't, create a new agPersonName() object and populate it with the submitted name.
      if ($nameObject == FALSE) {
        $nameObject = new agPersonName();
        $nameObject->person_name = $form->getObject()->person_name;
        $nameObject->save();
      }

      // See if there is an agPersonMjAgPersonName() object for this agPerson
      // and the agPersonNameType retrived by the above query.
      $joinObject = agDoctrineQuery::create()
              ->from('agPersonMjAgPersonName j')
              ->where(
                  'j.person_name_type_id = ? AND j.person_id = ?',
                  array($typeId, $this->getObject()->id)
              )
              ->execute()->getFirst();

      if ($joinObject instanceof agPersonMjAgPersonName) {
        $joinObject->person_name_id = $nameObject->id;
        // unlink() is called here because Doctrine still has the relation to the
        // old name object and will throw a duplicate entry error as it tries to
        // update that record's person_name value to the same value as $nameObject.
        // unlink() prevents this.
        $joinObject->unlink('agPersonName');
        $joinObject->save();
      } else {
        $joinObject = new agPersonMjAgPersonName();
        $joinObject->person_id = $this->getObject()->id;
        $joinObject->person_name_type_id = $typeId;
        $joinObject->person_name_id = $nameObject->id;
        $joinObject->priority = 1;
        $joinObject->save();
      }
      // Check if the agEmbeddedAgPersonNameForm() was populated on page render
      // but cleared before submission. If so, the related
      // agPersonMjAgPersonName object will be deleted.
    } elseif ($form->getObject()->isModified() && $form->getObject()->person_name == NULL) {
      $joinObject = agDoctrineQuery::create()
              ->from('agPersonMjAgPersonName j')
              ->where('j.person_name_type_id = ? AND j.person_id = ?', array($typeId, $this->getObject()->id))
              ->execute()->getFirst();
      $joinObject->delete();
      // Check if the form was unpopulated on render and submission.
      // If it was, return and unset the form, no processing is needed.
    } elseif (!$form->getObject()->isModified() && $form->getObject()->person_name == NULL && $form->getDefault('person_name') == NULL) {
      return;
    }
  }

  /**   * **************************************************************************
   * Saves data in an embedded email form.
   *
   * *************************************************************************** */
  public function saveEmailForm($key, $form, $values)
  {
    $form->updateObject($values);

    // Find the agEmailContactType()->id for the current form using its $key
    // (which corresponds to an agEmailContactType).
    $typeId = agDoctrineQuery::create()
            ->select('a.id')
            ->from('agEmailContactType a')
            ->where('a.email_contact_type = ?', $key)
            ->execute(NULL, Doctrine_Core::HYDRATE_SINGLE_SCALAR);

    if ($form->getObject()->isModified() && $form->getObject()->email_contact <> NULL) {
      $emailObject = Doctrine::getTable('agEmailContact')
              ->findByDql('email_contact = ?', $form->getObject()->email_contact)
              ->getFirst();

      if ($emailObject == FALSE) {
        $emailObject = new agEmailContact();
        $emailObject->email_contact = $form->getObject()->email_contact;
        $emailObject->save();
      }

      $joinObject = agDoctrineQuery::create()
              ->from('agEntityEmailContact j')
              ->where(
                  'j.email_contact_type_id = ? AND j.entity_id = ?',
                  array($typeId, $this->getObject()->entity_id)
              )
              ->execute()->getFirst();

      if ($joinObject instanceof agEntityEmailContact) {
        $joinObject->email_contact_id = $emailObject->id;
        $joinObject->unlink('agEmailContact');
        $joinObject->save();
      } else {
        $joinObject = new agEntityEmailContact();
        $joinObject->entity_id = $this->getObject()->entity_id;
        $joinObject->email_contact_type_id = $typeId;
        $joinObject->email_contact_id = $emailObject->id;
        $joinObject->priority = $typeId;
        $joinObject->save();
      }
    } elseif ($form->getObject()->isModified() && $form->getObject()->email_contact == NULL) {
      $joinObject = agDoctrineQuery::create()
              ->from('agEntityEmailContact j')
              ->where(
                  'j.email_contact_type_id = ? AND j.entity_id = ?',
                  array($typeId, $this->getObject()->entity_id)
              )
              ->execute()->getFirst();
      $joinObject->delete();
    } elseif (!$form->getObject()->isModified() && $form->getObject()->email_contact == NULL && $form->getDefault('email_contact') == NULL) {
      return;
    }
  }

  /*   * ***************************************************************************
   * Saves data in an embedded phone form.
   *
   * *************************************************************************** */

  public function savePhoneForm($key, $form, $values)
  {
    $form->updateObject($values);

    $typeId = agDoctrineQuery::create()
            ->select('a.id')
            ->from('agPhoneContactType a')
            ->where('a.phone_contact_type = ?', $key)
            ->execute(NULL, Doctrine_Core::HYDRATE_SINGLE_SCALAR);

    if ($form->getObject()->isModified() && $form->getObject()->phone_contact <> NULL) {
      $phoneObject = Doctrine::getTable('agPhoneContact')
              ->findByDql('phone_contact = ?', $form->getObject()->phone_contact)
              ->getFirst();

      if ($phoneObject == FALSE) {
        $phoneObject = new agPhoneContact();
        $phoneObject->phone_contact = $form->getObject()->phone_contact;
        $phoneObject->phone_format_id = $form->getObject()->phone_format_id;
        $phoneObject->save();
      }

      $joinObject = agDoctrineQuery::create()
              ->from('agEntityPhoneContact j')
              ->where(
                  'j.phone_contact_type_id = ? AND j.entity_id = ?',
                  array($typeId, $this->getObject()->entity_id)
              )
              ->execute()->getFirst();

      if ($joinObject instanceof agEntityPhoneContact) {
        $joinObject->phone_contact_id = $phoneObject->id;
        $joinObject->unlink('agPhoneContact');
        $joinObject->save();
      } else {
        $joinObject = new agEntityPhoneContact();
        $joinObject->entity_id = $this->getObject()->entity_id;
        $joinObject->phone_contact_type_id = $typeId;
        $joinObject->phone_contact_id = $phoneObject->id;
        $joinObject->priority = $typeId;
        $joinObject->save();
      }
    } elseif ($form->getObject()->isModified() && $form->getObject()->phone_contact == NULL) {
      $joinObject = agDoctrineQuery::create()
              ->from('agEntityPhoneContact j')
              ->where(
                  'j.phone_contact_type_id = ? AND j.entity_id = ?',
                  array($typeId, $this->getObject()->entity_id)
              )
              ->execute()->getFirst();
      $joinObject->delete();
    } elseif (!$form->getObject()->isModified() && $form->getObject()->phone_contact == NULL && $form->getDefault('phone_contact') == NULL) {
      return;
    }
  }

  /*****************************************************************************
  * Saves address data.
  *****************************************************************************/

  public function saveAddressForm($addressContainerForm)
  {
    // Set up some an agEntityAddressHelper() and some values we'll need as well
    $entAddHelper = new agEntityAddressHelper();
    $entId = $this->getObject()->getEntityId();
    $addressStandardId  = $entAddHelper->getAgAddressHelper()->getAddressStandardId();
    $geoSourceId = $this->getManualEntryGeoSource();

    // set up an interator and then process all of the address forms.
    $i = 0;
    foreach ($addressContainerForm->embeddedForms as $type => $addressForm) {
      // get the agAddressType->id based on the form key. Set the type id in the
      // address array.
      $typeId = agDoctrineQuery::create()
        ->select('id')
        ->from('agAddressContactType')
        ->where('address_contact_type = ?', $type)
        ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
      $address[0] = $typeId;

      // Check to see if all address value fields are empty. If they are, no
      // processing is needed.
      if($this->checkEmptyAddress($addressForm) === FALSE) {
        foreach ($addressForm->embeddedForms as $element => $value) {
          if($element <> 'Geo Data') {
            // Go through each agAddressValue form and get its value, if it exists.
            // put those values in the array.
            if($value->getObject()->value <> NULL) {
              $address[1][0][$value->getObject()->address_element_id] = $value->getObject()->value;
              if (empty($addresses[$entId][$i][1][1])) {
                $address[1][1] = $addressStandardId;
              }
            }
          } else {
            // Process the agGeoCoordinate forms and add their values to the array.
            // We only care if both are null, the validator stops one NULL and
            // one not NULL from getting in.
            if($value->getObject()->getLatitude() <> NULL || $value->getObject()->getLongitude() <> NULL) {
              $address[1][2] = array(array(array($value->getObject()->getLatitude(), $value->getObject()->getLongitude())), $geoSourceId);
            } else {
              if(!isset($emptyGeo)) $emptyGeo = array();
              $emptyGeo[$typeId] = $type;
            }
          }
        }
        // And add the $address array to the $addresses array.
        $addresses[$entId][$i] = $address;
      }
      unset($this->embeddedForms['Address'][$type]);
      $i++;
    }
    // And set all the addresses.
    if(isset($addresses)) {
      $entAddHelper->setEntityAddress($addresses, $geoSourceId, FALSE);
    }
    // Finally, unset any geo data that has been emptied.
    if(isset($emptyGeo)) {
      foreach($emptyGeo as $id => $type) {
        $addId = agDoctrineQuery::create()
            ->select('address_id')
            ->from('agEntityAddressContact')
            ->where('entity_id = ?', $entId)
              ->andWhere('address_contact_type_id = ?', $id)
            ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);

        if(!empty($addId)) {
          $addGeo = agDoctrineQuery::create()
              ->select('*')
              ->from('agAddressGeo')
              ->where('address_id = ?', $addId)
              ->fetchOne();
            if($addGeo instanceof agAddressGeo) $addGeo->delete();
        }
      }
    }
    unset($entAddHelper);
  }

  private function matchHash($hash, $entId, $typeId)
  {
    return agDoctrineQuery::create()
        ->select('*')
        ->from('agEntityAddressContact')
        ->where('entity_id = ?', $entId)
          ->andWhere('address_contact_type_id = ?', $typeId)
          ->andWhere('address_id = (SELECT add.id from agAddress add WHERE add.address_hash = ?)', $hash)
        ->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
  }
  /*
   * Returns the id for the manual entry geo source
   */
  private function getManualEntryGeoSource()
  {
    return agDoctrineQuery::create()
          ->select('id')
          ->from('agGeoSource')
          ->where('geo_source = "manual entry"')
          ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
  }

  /*
   * Checks an sfForm (one created as $addressContainer on page load by embedAddressForm())
   * to determine if any single field has submitted data.
   * If any field does have data, it returns false. If they're all empty, it returns true.
   *
   * Checks on the lat and long fields have been disabled, for now at least. Who needs
   * geo information when there's no address to link it to?
   *
   * @param $addressForm  An instance of sfForm(), created and populated in embedAddressForm()
   * @return Boolean      True if the subforms are all empty, False if any is populated.
   */
  private function checkEmptyAddress($addressForm)
  {
    $fieldValues = array();
    foreach($addressForm->embeddedForms as $element => $form) {
      $object = $form->getObject();
      if($element <> 'Geo Data') {
        if(!empty($object['value'])) $fieldValues[] = $object['value'];
      }
    }
    if(empty($fieldValues)) {
      return TRUE;
    }
    return FALSE;
  }

  /*****************************************************************************
   * Saves data in an embedded language form.
   *
   *****************************************************************************/
  public function saveLanguageForm($form, $joinId)
  {
    if ($form instanceof agEmbeddedAgPersonMjAgLanguageForm) {
      $joinQuery = agDoctrineQuery::create()
              ->select()
              ->from('agPersonMjAgLanguage')
              ->where('id = ?', $form->getObject()->id);

      if ($form->getObject()->language_id <> NULL) {
        //Create a new agPersonMjAgLanguageForm. Populate it with an existing object, if it exists.
        //check if the langauge value has changed between page render and form submission.
        //if it has, set the join object's lanquage to the new language.
        if ($form->getObject()->language_id <> $form->getDefault('language_id')) {
          // Have to get the object from the DB. Symfony errors out if we try to save the new one,
          // won't try to update, just does an insert.
          if ($join = $joinQuery->fetchOne()) {
            $join->language_id = $form->getObject()->language_id;
            $join->save();
          } else {
            $form->getObject()->person_id = $this->getObject()->id;
            $form->getObject()->save();
          }
          $joinId = $form->getObject()->id;
          $form->updateObject($form->getDefaults());
        } else {
          //If it didn't change, just unset it and be done w/ it.
          $joinId = (isset($form->getObject()->id)) ? $form->getObject()->id : NULL;
          ////Need this for the agEmbeddedAgPersonLanguageCompetencyForm section.
        }
      } else {
        //If the language form is blank, unset it.
//        unset($forms[$key]);
        //Then see if it was made blank between render and sumbission.
        if ($form->getObject()->language_id <> $form->getDefault('language_id')) {
          //if it was, delete the person-language join and all the associated data.
          //$join = $joinQuery->fetchOne();
          if ($join = $joinQuery->fetchOne()) {
            $competencies = $join->getAgPersonLanguageCompetency();
            $competencies->delete();
            $join->delete();
          }
          $joinId = NULL;
        }
      }
      return $joinId;
    }
    if ($form instanceof agEmbeddedAgPersonLanguageCompetencyForm) {
      // Check if a competency is selected, and also if there is still
      // an existing person-language join.
      if ($form->getObject()->language_competency_id <> NULL && $joinId <> NULL) {
        // Check if it's changed between render and submission.
        if ($form->getObject()->language_competency_id <> $form->getDefault('language_competency_id')) {
          if ($form->getObject()->person_language_id == NULL) {
            $form->getObject()->person_language_id = $joinId;
          }
          $form->getObject()->save();
        }
//        unset($forms[$key]);
      } else //If there's no competency ID selected, or if the agPersonMjAgLanguage
      //that uses the competency has been deleted.
      if ($form->getObject()->language_competency_id <> $form->getDefault('language_competency_id')) {//If it became blank between render and submit
        //  $form->getObject()->id = $form->getDefault('id');//Set the id and ...
        $form->updateObject($form->getDefaults());
        // ...delete the object.
        $form->getObject()->delete();
//        unset($forms[$key]);
      }
//      unset($forms[$key]);
      return $joinId;
    }
  }

  /*   * ************************************************************
   * Saves the forms embedded on the Person page.
   * @param $forms array of forms to save
   * @param $con the current doctrine connection instance
   * @return a call to the parent form's saveEmbeddedForms method
   * @todo break this method into smaller pieces
   * ************************************************************ */

  public function saveEmbeddedForms($con = NULL, $forms = NULL)
  {
    // Something better than isset might be useful here, get rid of the if.
    // For now though, do it this way otherwise, after the form's unset in
    // the saveDoB function, it'll try to get in here again and error.

    /**
     * Date of Birth
     * */
    if (isset($this->embeddedForms['Date of Birth'])) {
      $this->saveDateOfBirthForm($this->embeddedForms['Date of Birth']);
      unset($this->embeddedForms['Date of Birth']);
    }
    /**
     * Name
     * */
    if (isset($this->embeddedForms['Primary']['Name'])) {
      $b = $this->getEmbeddedForm('Primary')->getEmbeddedForm('Name')->getEmbeddedForms();
      foreach ($this->getEmbeddedForm('Primary')->getEmbeddedForm('Name')->getEmbeddedForms() as $key => $form) {
        $values = $this->values['Primary']['Name'][$key];
        $this->saveNameForm($key, $form, $values);
        unset($this->getEmbeddedForm('Primary')->embeddedForms['Name'][$key]);
      }
    }
    /**
     * Email
     * */
    if (isset($this->embeddedForms['Contact']['Email'])) {
      foreach ($this->getEmbeddedForm('Contact')->getEmbeddedForm('Email')->getEmbeddedForms() as $key => $form) {
        $values = $this->values['Contact']['Email'][$key];
        $this->saveEmailForm($key, $form, $values);
        unset($this->getEmbeddedForm('Contact')->embeddedForms['Email'][$key]);
      }
    }
    /**
     * Phone
     * This is slightly more complex than name or email. Phone values need to be
     * formatted first, as the DB holds them in 2125551212 form, but users will
     * input in (212) 555-1212 form (or 212.555.1212, etc.). Because the values
     * will always be processed, the form's object will always be seen as modified.
     * That's the purpose of calling state(Doctrine_Record::STATE_CLEAN) on the
     * object. After that, it will return unmodified. The phone number stored in
     * the $values array is also reformatted to be DB friendly.
     * */
    if (isset($this->embeddedForms['Contact']['Phone'])) {
      $phoneFormats = agDoctrineQuery::create()
              ->select('id, match_pattern')
              ->from('agPhoneFormatType')
              ->execute(array(), 'key_value_pair');
      foreach ($this->getEmbeddedForm('Contact')->getEmbeddedForm('Phone')->getEmbeddedForms() as $key => $form) {
        $form->getObject()->phone_contact = preg_replace('/[^0-9x]+/', '', $form->getObject()->phone_contact);
        foreach ($phoneFormats as $fKey => $phoneFormat) {
          if (preg_match($phoneFormat, $form->getObject()->phone_contact)) {
            $form->getObject()->phone_format_id = $fKey;
            break;
          }
        }
        if ($form->getObject()->phone_contact == $form->getDefault('phone_contact')) {
          $form->getObject()->state(Doctrine_Record::STATE_CLEAN);
        }
        $values = $this->values['Contact']['Phone'][$key];
        $values['phone_contact'] = preg_replace('/[^0-9x]+/', '', $values['phone_contact']);
        $this->savePhoneForm($key, $form, $values);
        unset($this->getEmbeddedForm('Contact')->embeddedForms['Phone'][$key]);
      }
    }
    /**
    * Address
    *
    *Save the address forms.
    * */
    if (isset($this->embeddedForms['Address'])) {
      $this->saveAddressForm($this->embeddedForms['Address']);
      unset($this->embeddedForms['Address']);
    }
    /**
     * Language
     *
     * The saveLanguageForm() function is in need of refactoring, which will most likely
     * necessitate some changes here as well
     * */
    if (isset($this->embeddedForms['Primary']['Languages'])) {
      foreach ($this->getEmbeddedForm('Primary')->getEmbeddedForm('Languages')->getEmbeddedForms() as $lKey => $languageForm) {
        foreach ($languageForm->embeddedForms as $fKey => $form) {
          $joinId = $this->saveLanguageForm($form, (isset($joinId) ? $joinId : NULL));
          unset($this->getEmbeddedForm('Primary')->getEmbeddedForm('Languages')->embeddedForms[$lKey]->embeddedForms[$fKey]);
        }
        unset($this->getEmbeddedForm('Primary')->embeddedForms['Languages'][$lKey]);
      }
    }
    /**
     * @todo The if() below needs to be removed/replaced. Right now it is preventing and invalid error on
     * some of the staff specific forms from PluginagStaffPersonForm.
     * */
    if (is_array($forms)) {
      foreach ($forms as $key => $form) {
        if ($form instanceof agEmbeddedStaffForm) {
          unset($forms[$key]);
        }
      }
    }
  }

  /**
   * This function is here to override BaseagPersonForm's doSave() method.
   * This is necessary to remove some of the save...List() functions that
   * Symfony autogenerates for many-to-many relations. The relations are more
   * complex than Symfony is able to auto-determine, and calling the save...List()
   * methods will often cause an error on save. The only lists needed are below.
   *
   * @param Doctrine_Connection $con
   * */
  protected function doSave($con = NULL)
  {
    $this->saveagNationalityList($con);
    $this->saveagReligionList($con);
    $this->saveagProfessionList($con);
    $this->saveagEthnicityList($con);
    $this->saveagSexList($con);
    $this->saveagMaritalStatusList($con);

    BaseFormDoctrine::doSave($con);
  }

  public function getStylesheets()
  {
    $css = parent::getStylesheets();
    $css['jquery/jquery.ui.custom.css'] = 'all';
    return $css;
  }

  public function getJavaScripts()
  {
    $js = parent::getJavaScripts();
    $js[] = 'jquery.ui.custom.js';
    return $js;
  }

}
