agGlobalParam:
  columns:
    id:
      primary: true
      type: integer(2)
      autoincrement: true
    host_id:
      type: integer(2)
      notnull: true
    datapoint:
      type: string(128)
      notnull: true
    value:
      type: string(128)
      notnull: true
    description:
      type: string(255)
  indexes:
    agGlobalParam_unq:
      fields: [host_id, datapoint]
      type: unique
  relations:
    agHost:
      class: agHost
      foreignAlias: agGlobalParam
      local: host_id
      foreign: id
agHost:
  columns:
    id:
      primary: true
      type: integer(2)
      autoincrement: true
    hostname:
      unique: true
      type: string(255)
      notnull: true
agEntity:
  columns:
    id:
      primary: true
      type: integer(5)
      notnull: true
      autoincrement: true
agEntityRelationshipType:
  columns:
    id:
      primary: true
      type: integer(2)
    entity_relationship_type:
      type: string(32)
      notnull: true
    entity_relationship_type_desc:
      type: string(255)
  indexes:
    UX_agEntityRelationshipType:
      fields: [entity_relationship_type]
      type: unique
agEntityRelationship:
  columns:
    id:
      primary: true
      type: integer(5)
      autoincrement: true
    entity_id1:
      type: integer(5)
      notnull: true
    entity_id2:
      type: integer(5)
      notnull: true
    entity_relationship_type_id:
      type: integer(2)
      notnull: true
    by_marriage:
      default: 0
      type: boolean
      notnull: true
    ex_relation:
      default: 0
      type: boolean
      notnull: true
  indexes:
    UX_agEntityRelationship:
      fields: [entity_id1, entity_id2, entity_relationship_type_id]
      type: unique
  relations:
    entity1:
      class: agEntity
      local: entity_id1
      foreign: id
    entity2:
      class: agEntity
      local: entity_id2
      foreign: id
    agEntityRelationshipType:
      local: entity_relationship_type_id
      foreign: id
agEntityRelationshipTypeInverse:
  columns:
    id:
      primary: true
      type: integer(2)
      autoincrement: true
    entity_relationship_type_id:
      type: integer(2)
      notnull: true
    entity_inverse_relationship_type_id:
      type: integer(2)
      notnull: true
  indexes:
    UX_agEntityRelationshipTypeInverse:
      fields: [entity_relationship_type_id, entity_inverse_relationship_type_id]
      type: unique
  relations:
    entity_relation_type:
      class: agEntityRelationshipType
      local: entity_relationship_type_id
      foreign: id
    entity_inverse_relation_type:
      class: agEntityRelationshipType
      local: entity_inverse_relationship_type_id
      foreign: id
actAs:
  Timestampable: 
